// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/ogen-go/ogen/validate"
)

// validateUniqueTag checks for duplicate items using hash-based detection.
func validateUniqueTag(items []Tag) (err error) {
	if len(items) <= 1 {
		return nil
	}

	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(*validate.DepthLimitError); ok {
				err = e
			} else {
				panic(r)
			}
		}
	}()

	type entry struct {
		item  Tag
		index int
	}
	buckets := make(map[uint64][]entry, len(items))

	for i, item := range items {
		hash := item.Hash()
		bucket := buckets[hash]

		for _, existing := range bucket {
			if item.Equal(existing.item, 0) {
				return &validate.DuplicateItemsError{
					Indices: []int{existing.index, i},
				}
			}
		}

		buckets[hash] = append(bucket, entry{item: item, index: i})
	}

	return nil
}
