// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"hash/fnv"
)

// Hash computes a hash value for Tag using FNV-1a.
// Equal objects must produce equal hashes.
func (a Tag) Hash() uint64 {
	h := fnv.New64a()

	// Hash primitive field: ID
	h.Write([]byte(fmt.Sprintf("%v", a.ID)))
	// Hash primitive field: Value
	h.Write([]byte(fmt.Sprintf("%v", a.Value)))
	return h.Sum64()
}
