// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// HTTPBasic provides HTTPBasic security value.
	HTTPBasic(ctx context.Context, operationName OperationName) (HTTPBasic, error)
}

// operationRolesHTTPBasic is a private map storing roles per operation.
var operationRolesHTTPBasic = map[string][]string{
	GetDeviceTokenOperation: []string{},
	GetJwtTokenOperation:    []string{},
}

// GetRolesForHTTPBasic returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForHTTPBasic(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForHTTPBasic(operation string) []string {
	roles, ok := operationRolesHTTPBasic[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Client) securityHTTPBasic(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.HTTPBasic(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"HTTPBasic\"")
	}
	req.SetBasicAuth(t.Username, t.Password)
	return nil
}
