// Code generated by ogen, DO NOT EDIT.
package api

type AddOutputPortDataQualityRunRes interface {
	addOutputPortDataQualityRunRes()
}

type ApproveOutputPortAsInputPortRes interface {
	approveOutputPortAsInputPortRes()
}

type ApproveOutputPortTechnicalAssetLinkRes interface {
	approveOutputPortTechnicalAssetLinkRes()
}

type BecomeAdminRes interface {
	becomeAdminRes()
}

type CheckAccessRes interface {
	checkAccessRes()
}

type CreateDataProductLifecycleRes interface {
	createDataProductLifecycleRes()
}

type CreateDataProductRes interface {
	createDataProductRes()
}

type CreateDataProductRoleAssignmentRes interface {
	createDataProductRoleAssignmentRes()
}

type CreateDataProductSettingRes interface {
	createDataProductSettingRes()
}

type CreateDataProductTypeRes interface {
	createDataProductTypeRes()
}

type CreateDomainRes interface {
	createDomainRes()
}

type CreateOutputPortRes interface {
	createOutputPortRes()
}

type CreateOutputPortRoleAssignmentRes interface {
	createOutputPortRoleAssignmentRes()
}

type CreateRoleRes interface {
	createRoleRes()
}

type CreateTagRes interface {
	createTagRes()
}

type CreateTechnicalAssetRes interface {
	createTechnicalAssetRes()
}

type CreateUserRes interface {
	createUserRes()
}

type DecideDataProductRoleAssignmentRes interface {
	decideDataProductRoleAssignmentRes()
}

type DecideGlobalRoleAssignmentRes interface {
	decideGlobalRoleAssignmentRes()
}

type DecideOutputPortRoleAssignmentRes interface {
	decideOutputPortRoleAssignmentRes()
}

type DeleteDataProductRoleAssignmentRes interface {
	deleteDataProductRoleAssignmentRes()
}

type DeleteGlobalRoleAssignmentRes interface {
	deleteGlobalRoleAssignmentRes()
}

type DeleteOutputPortQueryStatRes interface {
	deleteOutputPortQueryStatRes()
}

type DeleteOutputPortRoleAssignmentRes interface {
	deleteOutputPortRoleAssignmentRes()
}

type DenyOutputPortAsInputPortRes interface {
	denyOutputPortAsInputPortRes()
}

type DenyOutputPortTechnicalAssetLinkRes interface {
	denyOutputPortTechnicalAssetLinkRes()
}

type GetAWSCredentialsRes interface {
	getAWSCredentialsRes()
}

type GetDataProductEventHistoryRes interface {
	getDataProductEventHistoryRes()
}

type GetDataProductInputPortsRes interface {
	getDataProductInputPortsRes()
}

type GetDataProductOutputPortsRes interface {
	getDataProductOutputPortsRes()
}

type GetDataProductRes interface {
	getDataProductRes()
}

type GetDataProductRolledUpTagsRes interface {
	getDataProductRolledUpTagsRes()
}

type GetDataProductSettingsNamespaceSuggestionRes interface {
	getDataProductSettingsNamespaceSuggestionRes()
}

type GetDataProductSettingsRes interface {
	getDataProductSettingsRes()
}

type GetDataProductTechnicalAssetsRes interface {
	getDataProductTechnicalAssetsRes()
}

type GetDataProductTypeRes interface {
	getDataProductTypeRes()
}

type GetDataProductsRes interface {
	getDataProductsRes()
}

type GetDeviceTokenRes interface {
	getDeviceTokenRes()
}

type GetDomainRes interface {
	getDomainRes()
}

type GetEnvironmentRes interface {
	getEnvironmentRes()
}

type GetInputPortsForOutputPortRes interface {
	getInputPortsForOutputPortRes()
}

type GetJwtTokenRes interface {
	getJwtTokenRes()
}

type GetLatestDataQualitySummaryForOutputPortRes interface {
	getLatestDataQualitySummaryForOutputPortRes()
}

type GetOutputPortCuratedQueriesRes interface {
	getOutputPortCuratedQueriesRes()
}

type GetOutputPortQueryStatsRes interface {
	getOutputPortQueryStatsRes()
}

type GetOutputPortRes interface {
	getOutputPortRes()
}

type GetOutputPortsEventHistoryRes interface {
	getOutputPortsEventHistoryRes()
}

type GetPlatformServiceConfigRes interface {
	getPlatformServiceConfigRes()
}

type GetPlatformServicesRes interface {
	getPlatformServicesRes()
}

type GetPluginFormRes interface {
	getPluginFormRes()
}

type GetPluginURLRes interface {
	getPluginURLRes()
}

type GetRolesRes interface {
	getRolesRes()
}

type GetSinglePlatformServiceConfigurationRes interface {
	getSinglePlatformServiceConfigurationRes()
}

type GetTechnicalAssetEventHistoryRes interface {
	getTechnicalAssetEventHistoryRes()
}

type GetTechnicalAssetRes interface {
	getTechnicalAssetRes()
}

type LinkInputPortsToDataProductRes interface {
	linkInputPortsToDataProductRes()
}

type LinkOutputPortToTechnicalAssetRes interface {
	linkOutputPortToTechnicalAssetRes()
}

type ListDataProductRoleAssignmentsRes interface {
	listDataProductRoleAssignmentsRes()
}

type ListGlobalRoleAssignmentsRes interface {
	listGlobalRoleAssignmentsRes()
}

type ListOutputPortRoleAssignmentsRes interface {
	listOutputPortRoleAssignmentsRes()
}

type MigrateDataProductTypeRes interface {
	migrateDataProductTypeRes()
}

type MigrateDomainRes interface {
	migrateDomainRes()
}

type ModifyDataProductRoleAssignmentRes interface {
	modifyDataProductRoleAssignmentRes()
}

type ModifyOutputPortRoleAssignmentRes interface {
	modifyOutputPortRoleAssignmentRes()
}

type OverwriteOutputPortDataQualitySummaryRes interface {
	overwriteOutputPortDataQualitySummaryRes()
}

type RemoveDataProductLifecycleRes interface {
	removeDataProductLifecycleRes()
}

type RemoveDataProductRes interface {
	removeDataProductRes()
}

type RemoveDataProductSettingRes interface {
	removeDataProductSettingRes()
}

type RemoveDataProductTypeRes interface {
	removeDataProductTypeRes()
}

type RemoveDomainRes interface {
	removeDomainRes()
}

type RemoveOutputPortAsInputPortRes interface {
	removeOutputPortAsInputPortRes()
}

type RemoveOutputPortRes interface {
	removeOutputPortRes()
}

type RemoveRoleRes interface {
	removeRoleRes()
}

type RemoveTagRes interface {
	removeTagRes()
}

type RemoveTechnicalAssetRes interface {
	removeTechnicalAssetRes()
}

type RemoveUserNotificationRes interface {
	removeUserNotificationRes()
}

type RemoveUserRes interface {
	removeUserRes()
}

type RenderTechnicalAssetAccessPathRes interface {
	renderTechnicalAssetAccessPathRes()
}

type ReplaceOutputPortCuratedQueriesRes interface {
	replaceOutputPortCuratedQueriesRes()
}

type RequestDataProductRoleAssignmentRes interface {
	requestDataProductRoleAssignmentRes()
}

type RequestOutputPortRoleAssignmentRes interface {
	requestOutputPortRoleAssignmentRes()
}

type SanitizeResourceNameRes interface {
	sanitizeResourceNameRes()
}

type SearchOutputPortsRes interface {
	searchOutputPortsRes()
}

type SetCanBecomeAdminRes interface {
	setCanBecomeAdminRes()
}

type SetValueForDataProductRes interface {
	setValueForDataProductRes()
}

type SetValueForOutputPortRes interface {
	setValueForOutputPortRes()
}

type UnlinkInputPortFromDataProductRes interface {
	unlinkInputPortFromDataProductRes()
}

type UnlinkOutputPortFromTechnicalAssetRes interface {
	unlinkOutputPortFromTechnicalAssetRes()
}

type UpdateDataProductAboutRes interface {
	updateDataProductAboutRes()
}

type UpdateDataProductLifecycleRes interface {
	updateDataProductLifecycleRes()
}

type UpdateDataProductRes interface {
	updateDataProductRes()
}

type UpdateDataProductSettingRes interface {
	updateDataProductSettingRes()
}

type UpdateDataProductStatusRes interface {
	updateDataProductStatusRes()
}

type UpdateDataProductTypeRes interface {
	updateDataProductTypeRes()
}

type UpdateDataProductUsageRes interface {
	updateDataProductUsageRes()
}

type UpdateDomainRes interface {
	updateDomainRes()
}

type UpdateOutputPortAboutRes interface {
	updateOutputPortAboutRes()
}

type UpdateOutputPortQueryStatsRes interface {
	updateOutputPortQueryStatsRes()
}

type UpdateOutputPortRes interface {
	updateOutputPortRes()
}

type UpdateOutputPortStatusRes interface {
	updateOutputPortStatusRes()
}

type UpdateRoleRes interface {
	updateRoleRes()
}

type UpdateTagRes interface {
	updateTagRes()
}

type UpdateTechnicalAssetRes interface {
	updateTechnicalAssetRes()
}

type UpdateTechnicalAssetStatusRes interface {
	updateTechnicalAssetStatusRes()
}

type UpdateThemeSettingsRes interface {
	updateThemeSettingsRes()
}

type ValidateDataProductSettingsNamespaceRes interface {
	validateDataProductSettingsNamespaceRes()
}

type ValidateResourceNameRes interface {
	validateResourceNameRes()
}
