// Code generated by ogen, DO NOT EDIT.

package api

import "github.com/ogen-go/ogen/validate"

// Equal compares two Tag instances for equality.
// The depth parameter prevents infinite recursion on nested objects.
func (a Tag) Equal(b Tag, depth int) bool {
	if depth > 10 {
		panic(&validate.DepthLimitError{
			MaxDepth: 10,
			TypeName: "Tag",
		})
	}

	if a.ID != b.ID {
		return false
	}
	if a.Value != b.Value {
		return false
	}
	return true
}
