// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/google/uuid"
)

// AddOutputPortDataQualityRunParams is parameters of add_output_port_data_quality_run operation.
type AddOutputPortDataQualityRunParams struct {
	DataProductID uuid.UUID
	ID            uuid.UUID
}

// ApproveOutputPortAsInputPortParams is parameters of approve_output_port_as_input_port operation.
type ApproveOutputPortAsInputPortParams struct {
	DataProductID uuid.UUID
	OutputPortID  uuid.UUID
}

// ApproveOutputPortTechnicalAssetLinkParams is parameters of approve_output_port_technical_asset_link operation.
type ApproveOutputPortTechnicalAssetLinkParams struct {
	DataProductID uuid.UUID
	OutputPortID  uuid.UUID
}

// CheckAccessParams is parameters of check_access operation.
type CheckAccessParams struct {
	Action   AuthorizationAction
	Resource OptUUID `json:",omitempty,omitzero"`
	Domain   OptUUID `json:",omitempty,omitzero"`
}

// CreateOutputPortParams is parameters of create_output_port operation.
type CreateOutputPortParams struct {
	DataProductID uuid.UUID
}

// CreateTechnicalAssetParams is parameters of create_technical_asset operation.
type CreateTechnicalAssetParams struct {
	DataProductID uuid.UUID
}

// DecideDataProductRoleAssignmentParams is parameters of decide_data_product_role_assignment operation.
type DecideDataProductRoleAssignmentParams struct {
	ID uuid.UUID
}

// DecideGlobalRoleAssignmentParams is parameters of decide_global_role_assignment operation.
type DecideGlobalRoleAssignmentParams struct {
	ID uuid.UUID
}

// DecideOutputPortRoleAssignmentParams is parameters of decide_output_port_role_assignment operation.
type DecideOutputPortRoleAssignmentParams struct {
	ID uuid.UUID
}

// DeleteDataProductRoleAssignmentParams is parameters of delete_data_product_role_assignment operation.
type DeleteDataProductRoleAssignmentParams struct {
	ID uuid.UUID
}

// DeleteGlobalRoleAssignmentParams is parameters of delete_global_role_assignment operation.
type DeleteGlobalRoleAssignmentParams struct {
	ID uuid.UUID
}

// DeleteOutputPortQueryStatParams is parameters of delete_output_port_query_stat operation.
type DeleteOutputPortQueryStatParams struct {
	DataProductID uuid.UUID
	ID            uuid.UUID
}

// DeleteOutputPortRoleAssignmentParams is parameters of delete_output_port_role_assignment operation.
type DeleteOutputPortRoleAssignmentParams struct {
	ID uuid.UUID
}

// DenyOutputPortAsInputPortParams is parameters of deny_output_port_as_input_port operation.
type DenyOutputPortAsInputPortParams struct {
	DataProductID uuid.UUID
	OutputPortID  uuid.UUID
}

// DenyOutputPortTechnicalAssetLinkParams is parameters of deny_output_port_technical_asset_link operation.
type DenyOutputPortTechnicalAssetLinkParams struct {
	DataProductID uuid.UUID
	OutputPortID  uuid.UUID
}

// GetAWSCredentialsParams is parameters of get_aws_credentials operation.
type GetAWSCredentialsParams struct {
	DataProductName string
	Environment     string
}

// GetDataProductParams is parameters of get_data_product operation.
type GetDataProductParams struct {
	ID uuid.UUID
}

// GetDataProductEventHistoryParams is parameters of get_data_product_event_history operation.
type GetDataProductEventHistoryParams struct {
	ID uuid.UUID
}

// GetDataProductInputPortsParams is parameters of get_data_product_input_ports operation.
type GetDataProductInputPortsParams struct {
	ID uuid.UUID
}

// GetDataProductOutputPortsParams is parameters of get_data_product_output_ports operation.
type GetDataProductOutputPortsParams struct {
	DataProductID uuid.UUID
}

// GetDataProductRolledUpTagsParams is parameters of get_data_product_rolled_up_tags operation.
type GetDataProductRolledUpTagsParams struct {
	ID uuid.UUID
}

// GetDataProductSettingsParams is parameters of get_data_product_settings operation.
type GetDataProductSettingsParams struct {
	ID uuid.UUID
}

// GetDataProductSettingsNamespaceSuggestionParams is parameters of get_data_product_settings_namespace_suggestion operation.
type GetDataProductSettingsNamespaceSuggestionParams struct {
	Name string
}

// GetDataProductTechnicalAssetsParams is parameters of get_data_product_technical_assets operation.
type GetDataProductTechnicalAssetsParams struct {
	DataProductID uuid.UUID
}

// GetDataProductTypeParams is parameters of get_data_product_type operation.
type GetDataProductTypeParams struct {
	ID uuid.UUID
}

// GetDataProductsParams is parameters of get_data_products operation.
type GetDataProductsParams struct {
	FilterToUserWithAssigment OptUUID `json:",omitempty,omitzero"`
}

// GetDeviceTokenParams is parameters of get_device_token operation.
type GetDeviceTokenParams struct {
	ClientID string
	Scope    OptString `json:",omitempty,omitzero"`
}

// GetDomainParams is parameters of get_domain operation.
type GetDomainParams struct {
	ID uuid.UUID
}

// GetEnvironmentParams is parameters of get_environment operation.
type GetEnvironmentParams struct {
	ID uuid.UUID
}

// GetInputPortsForOutputPortParams is parameters of get_input_ports_for_output_port operation.
type GetInputPortsForOutputPortParams struct {
	DataProductID uuid.UUID
	OutputPortID  uuid.UUID
}

// GetJwtTokenParams is parameters of get_jwt_token operation.
type GetJwtTokenParams struct {
	ClientID   string
	DeviceCode string
	GrantType  string
}

// GetLatestDataQualitySummaryForOutputPortParams is parameters of get_latest_data_quality_summary_for_output_port operation.
type GetLatestDataQualitySummaryForOutputPortParams struct {
	DataProductID uuid.UUID
	ID            uuid.UUID
}

// GetOutputPortParams is parameters of get_output_port operation.
type GetOutputPortParams struct {
	DataProductID uuid.UUID
	ID            uuid.UUID
}

// GetOutputPortCuratedQueriesParams is parameters of get_output_port_curated_queries operation.
type GetOutputPortCuratedQueriesParams struct {
	DataProductID uuid.UUID
	ID            uuid.UUID
}

// GetOutputPortQueryStatsParams is parameters of get_output_port_query_stats operation.
type GetOutputPortQueryStatsParams struct {
	DataProductID uuid.UUID
	ID            uuid.UUID
	Granularity   OptQueryStatsGranularity `json:",omitempty,omitzero"`
	DayRange      OptInt                   `json:",omitempty,omitzero"`
}

// GetOutputPortsEventHistoryParams is parameters of get_output_ports_event_history operation.
type GetOutputPortsEventHistoryParams struct {
	DataProductID uuid.UUID
	ID            uuid.UUID
}

// GetPlatformServiceConfigParams is parameters of get_platform_service_config operation.
type GetPlatformServiceConfigParams struct {
	ID        uuid.UUID
	ServiceID uuid.UUID
}

// GetPlatformServicesParams is parameters of get_platform_services operation.
type GetPlatformServicesParams struct {
	ID uuid.UUID
}

// GetPluginFormParams is parameters of get_plugin_form operation.
type GetPluginFormParams struct {
	PluginName string
}

// GetPluginURLParams is parameters of get_plugin_url operation.
type GetPluginURLParams struct {
	PluginName  string
	ID          uuid.UUID
	Environment OptString `json:",omitempty,omitzero"`
}

// GetRolesParams is parameters of get_roles operation.
type GetRolesParams struct {
	Scope Scope
}

// GetSinglePlatformServiceConfigurationParams is parameters of get_single_platform_service_configuration operation.
type GetSinglePlatformServiceConfigurationParams struct {
	ConfigID uuid.UUID
}

// GetTechnicalAssetParams is parameters of get_technical_asset operation.
type GetTechnicalAssetParams struct {
	DataProductID uuid.UUID
	ID            uuid.UUID
}

// GetTechnicalAssetEventHistoryParams is parameters of get_technical_asset_event_history operation.
type GetTechnicalAssetEventHistoryParams struct {
	DataProductID uuid.UUID
	ID            uuid.UUID
}

// LinkInputPortsToDataProductParams is parameters of link_input_ports_to_data_product operation.
type LinkInputPortsToDataProductParams struct {
	ID uuid.UUID
}

// LinkOutputPortToTechnicalAssetParams is parameters of link_output_port_to_technical_asset operation.
type LinkOutputPortToTechnicalAssetParams struct {
	DataProductID uuid.UUID
	OutputPortID  uuid.UUID
}

// ListDataProductRoleAssignmentsParams is parameters of list_data_product_role_assignments operation.
type ListDataProductRoleAssignmentsParams struct {
	DataProductID OptUUID           `json:",omitempty,omitzero"`
	UserID        OptUUID           `json:",omitempty,omitzero"`
	RoleID        OptUUID           `json:",omitempty,omitzero"`
	Decision      OptDecisionStatus `json:",omitempty,omitzero"`
}

// ListGlobalRoleAssignmentsParams is parameters of list_global_role_assignments operation.
type ListGlobalRoleAssignmentsParams struct {
	UserID OptUUID `json:",omitempty,omitzero"`
	RoleID OptUUID `json:",omitempty,omitzero"`
}

// ListOutputPortRoleAssignmentsParams is parameters of list_output_port_role_assignments operation.
type ListOutputPortRoleAssignmentsParams struct {
	OutputPortID OptUUID           `json:",omitempty,omitzero"`
	UserID       OptUUID           `json:",omitempty,omitzero"`
	RoleID       OptUUID           `json:",omitempty,omitzero"`
	Decision     OptDecisionStatus `json:",omitempty,omitzero"`
}

// MigrateDataProductTypeParams is parameters of migrate_data_product_type operation.
type MigrateDataProductTypeParams struct {
	FromID uuid.UUID
	ToID   uuid.UUID
}

// MigrateDomainParams is parameters of migrate_domain operation.
type MigrateDomainParams struct {
	FromID uuid.UUID
	ToID   uuid.UUID
}

// ModifyDataProductRoleAssignmentParams is parameters of modify_data_product_role_assignment operation.
type ModifyDataProductRoleAssignmentParams struct {
	ID uuid.UUID
}

// ModifyOutputPortRoleAssignmentParams is parameters of modify_output_port_role_assignment operation.
type ModifyOutputPortRoleAssignmentParams struct {
	ID uuid.UUID
}

// OverwriteOutputPortDataQualitySummaryParams is parameters of overwrite_output_port_data_quality_summary operation.
type OverwriteOutputPortDataQualitySummaryParams struct {
	DataProductID uuid.UUID
	ID            uuid.UUID
	SummaryID     uuid.UUID
}

// RemoveDataProductParams is parameters of remove_data_product operation.
type RemoveDataProductParams struct {
	ID uuid.UUID
}

// RemoveDataProductLifecycleParams is parameters of remove_data_product_lifecycle operation.
type RemoveDataProductLifecycleParams struct {
	ID uuid.UUID
}

// RemoveDataProductSettingParams is parameters of remove_data_product_setting operation.
type RemoveDataProductSettingParams struct {
	ID uuid.UUID
}

// RemoveDataProductTypeParams is parameters of remove_data_product_type operation.
type RemoveDataProductTypeParams struct {
	ID uuid.UUID
}

// RemoveDomainParams is parameters of remove_domain operation.
type RemoveDomainParams struct {
	ID uuid.UUID
}

// RemoveOutputPortParams is parameters of remove_output_port operation.
type RemoveOutputPortParams struct {
	DataProductID uuid.UUID
	ID            uuid.UUID
}

// RemoveOutputPortAsInputPortParams is parameters of remove_output_port_as_input_port operation.
type RemoveOutputPortAsInputPortParams struct {
	DataProductID uuid.UUID
	OutputPortID  uuid.UUID
}

// RemoveRoleParams is parameters of remove_role operation.
type RemoveRoleParams struct {
	ID uuid.UUID
}

// RemoveTagParams is parameters of remove_tag operation.
type RemoveTagParams struct {
	ID uuid.UUID
}

// RemoveTechnicalAssetParams is parameters of remove_technical_asset operation.
type RemoveTechnicalAssetParams struct {
	DataProductID uuid.UUID
	ID            uuid.UUID
}

// RemoveUserParams is parameters of remove_user operation.
type RemoveUserParams struct {
	ID uuid.UUID
}

// RemoveUserNotificationParams is parameters of remove_user_notification operation.
type RemoveUserNotificationParams struct {
	ID uuid.UUID
}

// ReplaceOutputPortCuratedQueriesParams is parameters of replace_output_port_curated_queries operation.
type ReplaceOutputPortCuratedQueriesParams struct {
	DataProductID uuid.UUID
	ID            uuid.UUID
}

// SanitizeResourceNameParams is parameters of sanitize_resource_name operation.
type SanitizeResourceNameParams struct {
	Name string
}

// SearchOutputPortsParams is parameters of search_output_ports operation.
type SearchOutputPortsParams struct {
	Query               OptString `json:",omitempty,omitzero"`
	Limit               OptInt    `json:",omitempty,omitzero"`
	CurrentUserAssigned OptBool   `json:",omitempty,omitzero"`
}

// SetValueForDataProductParams is parameters of set_value_for_data_product operation.
type SetValueForDataProductParams struct {
	ID        uuid.UUID
	SettingID uuid.UUID
	Value     string
}

// SetValueForOutputPortParams is parameters of set_value_for_output_port operation.
type SetValueForOutputPortParams struct {
	DataProductID uuid.UUID
	ID            uuid.UUID
	SettingID     uuid.UUID
	Value         string
}

// UnlinkInputPortFromDataProductParams is parameters of unlink_input_port_from_data_product operation.
type UnlinkInputPortFromDataProductParams struct {
	ID          uuid.UUID
	InputPortID uuid.UUID
}

// UnlinkOutputPortFromTechnicalAssetParams is parameters of unlink_output_port_from_technical_asset operation.
type UnlinkOutputPortFromTechnicalAssetParams struct {
	DataProductID uuid.UUID
	OutputPortID  uuid.UUID
}

// UpdateDataProductParams is parameters of update_data_product operation.
type UpdateDataProductParams struct {
	ID uuid.UUID
}

// UpdateDataProductAboutParams is parameters of update_data_product_about operation.
type UpdateDataProductAboutParams struct {
	ID uuid.UUID
}

// UpdateDataProductLifecycleParams is parameters of update_data_product_lifecycle operation.
type UpdateDataProductLifecycleParams struct {
	ID uuid.UUID
}

// UpdateDataProductSettingParams is parameters of update_data_product_setting operation.
type UpdateDataProductSettingParams struct {
	ID uuid.UUID
}

// UpdateDataProductStatusParams is parameters of update_data_product_status operation.
type UpdateDataProductStatusParams struct {
	ID uuid.UUID
}

// UpdateDataProductTypeParams is parameters of update_data_product_type operation.
type UpdateDataProductTypeParams struct {
	ID uuid.UUID
}

// UpdateDataProductUsageParams is parameters of update_data_product_usage operation.
type UpdateDataProductUsageParams struct {
	ID uuid.UUID
}

// UpdateDomainParams is parameters of update_domain operation.
type UpdateDomainParams struct {
	ID uuid.UUID
}

// UpdateOutputPortParams is parameters of update_output_port operation.
type UpdateOutputPortParams struct {
	DataProductID uuid.UUID
	ID            uuid.UUID
}

// UpdateOutputPortAboutParams is parameters of update_output_port_about operation.
type UpdateOutputPortAboutParams struct {
	DataProductID uuid.UUID
	ID            uuid.UUID
}

// UpdateOutputPortQueryStatsParams is parameters of update_output_port_query_stats operation.
type UpdateOutputPortQueryStatsParams struct {
	DataProductID uuid.UUID
	ID            uuid.UUID
}

// UpdateOutputPortStatusParams is parameters of update_output_port_status operation.
type UpdateOutputPortStatusParams struct {
	DataProductID uuid.UUID
	ID            uuid.UUID
}

// UpdateRoleParams is parameters of update_role operation.
type UpdateRoleParams struct {
	ID uuid.UUID
}

// UpdateTagParams is parameters of update_tag operation.
type UpdateTagParams struct {
	ID uuid.UUID
}

// UpdateTechnicalAssetParams is parameters of update_technical_asset operation.
type UpdateTechnicalAssetParams struct {
	DataProductID uuid.UUID
	ID            uuid.UUID
}

// UpdateTechnicalAssetStatusParams is parameters of update_technical_asset_status operation.
type UpdateTechnicalAssetStatusParams struct {
	DataProductID uuid.UUID
	ID            uuid.UUID
}

// ValidateDataProductSettingsNamespaceParams is parameters of validate_data_product_settings_namespace operation.
type ValidateDataProductSettingsNamespaceParams struct {
	Namespace string
	Scope     DataProductSettingScope
}

// ValidateResourceNameParams is parameters of validate_resource_name operation.
type ValidateResourceNameParams struct {
	ResourceName  string
	Model         ResourceNameModel
	DataProductID OptUUID `json:",omitempty,omitzero"`
}
