// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *DataProductLifeCycleCreate) setDefaults() {
	{
		val := bool(false)
		s.IsDefault.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DataProductLifeCycleUpdate) setDefaults() {
	{
		val := bool(false)
		s.IsDefault.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DataProductSetting) setDefaults() {
	{
		val := int(100)
		s.Order.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DataProductSettingCreate) setDefaults() {
	{
		val := int(100)
		s.Order.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DataProductSettingUpdate) setDefaults() {
	{
		val := int(100)
		s.Order.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DataProductSettingsGetItem) setDefaults() {
	{
		val := int(100)
		s.Order.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DatabricksTechnicalAssetConfiguration) setDefaults() {
	{
		val := string("")
		s.Schema.SetTo(val)
	}
	{
		val := string("*")
		s.Table.SetTo(val)
	}
	{
		val := string("")
		s.BucketIdentifier.SetTo(val)
	}
	{
		val := string("")
		s.CatalogPath.SetTo(val)
	}
	{
		val := string("")
		s.TablePath.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *Environment) setDefaults() {
	{
		val := bool(false)
		s.IsDefault.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EnvironmentGetItem) setDefaults() {
	{
		val := bool(false)
		s.IsDefault.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GlueTechnicalAssetConfiguration) setDefaults() {
	{
		val := string("")
		s.DatabaseSuffix.SetTo(val)
	}
	{
		val := string("*")
		s.Table.SetTo(val)
	}
	{
		val := string("")
		s.BucketIdentifier.SetTo(val)
	}
	{
		val := string("")
		s.DatabasePath.SetTo(val)
	}
	{
		val := string("")
		s.TablePath.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OSISemanticModelTechnicalAssetConfiguration) setDefaults() {
	{
		val := string("")
		s.ModelName.SetTo(val)
	}
	{
		val := string("")
		s.FilePath.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PlatformTile) setDefaults() {
	{
		val := bool(true)
		s.HasEnvironments.SetTo(val)
	}
	{
		val := bool(true)
		s.HasConfig.SetTo(val)
	}
	{
		val := bool(true)
		s.ShowInForm.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PostgreSQLTechnicalAssetConfiguration) setDefaults() {
	{
		val := string("")
		s.Schema.SetTo(val)
	}
	{
		val := string("*")
		s.Table.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RedshiftTechnicalAssetConfiguration) setDefaults() {
	{
		val := string("")
		s.Schema.SetTo(val)
	}
	{
		val := string("*")
		s.Table.SetTo(val)
	}
	{
		val := string("")
		s.BucketIdentifier.SetTo(val)
	}
	{
		val := string("")
		s.DatabasePath.SetTo(val)
	}
	{
		val := string("")
		s.TablePath.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *S3TechnicalAssetConfiguration) setDefaults() {
	{
		val := string("")
		s.Suffix.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SnowflakeTechnicalAssetConfiguration) setDefaults() {
	{
		val := string("")
		s.Schema.SetTo(val)
	}
	{
		val := string("*")
		s.Table.SetTo(val)
	}
	{
		val := string("")
		s.BucketIdentifier.SetTo(val)
	}
	{
		val := string("")
		s.DatabasePath.SetTo(val)
	}
	{
		val := string("")
		s.TablePath.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UIElementMetadataResponse) setDefaults() {
	{
		val := bool(false)
		s.NotConfigured.SetTo(val)
	}
	{
		val := string("Resulting path")
		s.ResultLabel.SetTo(val)
	}
	{
		val := string("The path you can access through this technical asset")
		s.ResultTooltip.SetTo(val)
	}
	{
		val := bool(true)
		s.ShowInForm.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UIElementRadio) setDefaults() {
	{
		val := int(1)
		s.MaxCount.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UIElementSelect) setDefaults() {
	{
		val := int(1)
		s.MaxCount.SetTo(val)
	}
}
