export enum TagTypes {
    DataProduct = 'DataProduct',
    DataProductRoleAssignments = 'DataProductRoleAssignments',
    GlobalRoleAssignments = 'GlobalRoleAssignments',
    UserOutputPorts = 'UserOutputPorts',
    UserTechnicalAssets = 'UserTechnicalAssets',
    DataProductType = 'DataProductType',
    Tags = 'Tags',
    DataProductLifecycle = 'DataProductLifecycle',
    DataProductSetting = 'DataProductSetting',
    CurrentUser = 'CurrentUser',
    User = 'User',
    Auth = 'Auth',
    Role = 'Role',
    Environment = 'Environment',
    OutputPort = 'OutputPort',
    OutputPortInputPorts = 'OutputPortInputPorts',
    DataProductOutputPorts = 'DataProductInputPorts',
    DataProductTechnicalAssets = 'DataProductInputPorts',
    DataProductInputPorts = 'DataProductInputPorts',
    DataProductRolledUpTags = 'DataProductRolledUpTags',
    OutputPortRoleAssignments = 'OutputPortRoleAssignments',
    Domain = 'Domain',
    TechnicalAsset = 'TechnicalAsset',
    Graph = 'Graph',
    Platform = 'Platform',
    PlatformService = 'PlatformService',
    PlatformServiceConfig = 'PlatformServiceConfig',
    EnvironmentConfigs = 'EnvironmentConfigs',
    Version = 'Version',
    ThemeSettings = 'ThemeSettings',
    History = 'History',
    Notifications = 'Notifications',
    PendingAction = 'PendingAction',
}

export const STATIC_TAG_ID = {
    LIST: 'LIST',
    CURRENT_USER: 'CURRENT_USER',
} as const;
