import os
import re
from pathlib import Path


def generate_event_handler_base():
    """Scans generated models and writes out the Abstract Base Class."""
    print("🔍 Scanning generated models for CloudEvents...")

    sdk_dir = Path(__file__).parent.parent / "sdk"
    models_dir = sdk_dir / "api_client" / "models"
    if not models_dir.exists():
        raise FileNotFoundError(f"Could not locate models directory at {models_dir}")

    events = []

    class_pattern = re.compile(r"class\s+(CloudEvent\w+):")
    type_pattern = re.compile(r'type_:\s*Literal\["([^"]+)"]')
    data_pattern = re.compile(r"data:\s*([A-Z]\w+)")

    # Scan every Python file in the models directory
    for file_path in models_dir.glob("*.py"):
        content = file_path.read_text()

        class_match = class_pattern.search(content)
        type_match = type_pattern.search(content)
        data_match = data_pattern.search(content)

        if class_match and type_match and data_match:
            class_name = class_match.group(1)
            event_type = type_match.group(1)
            inner_class_name = data_match.group(1)
            method_name = f"on_{event_type.replace('.', '_').replace('-', '_')}"

            events.append(
                {
                    "class_name": class_name,
                    "inner_class_name": inner_class_name,
                    "event_type": event_type,
                    "method_name": method_name,
                }
            )
        elif class_match and not (type_match and data_match):
            raise FileNotFoundError(f"Could not process class '{class_match.group(1)}'")

    if not events:
        print("⚠️ No CloudEvent models found.")
        return

    print(f"✨ Found {len(events)} events. Generating Abstract Base Class...")

    # Build up strings for the template

    all_imports = set()
    for e in events:
        all_imports.add(e["class_name"])
        all_imports.add(e["inner_class_name"])
    imports = "\n    ".join((i + "," for i in sorted(all_imports)))

    dispatch_blocks = ["        parsed_event: Any"]
    for i, e in enumerate(events):
        keyword = "if" if i == 0 else "elif"
        dispatch_blocks.append(f"""        {keyword} event_type == "{e["event_type"]}":
            parsed_event = {e["class_name"]}.from_dict(payload)
            return await self.{e["method_name"]}(parsed_event.data)""")

    dispatch_code = "\n".join(dispatch_blocks)

    abstract_methods = []
    for e in events:
        abstract_methods.append(f"""    @abstractmethod
    async def {e["method_name"]}(self, data: {e["inner_class_name"]}) -> Any:
        \"\"\"Handler for the parsed payload of '{e["event_type"]}'\"\"\"
        pass""")

    abstract_methods_code = "\n\n".join(abstract_methods)

    # The full file template
    base_class_content = f"""# CODE GENERATED BY {os.path.basename(__file__)}. DO NOT EDIT MANUALLY.
# fmt: off
from abc import ABC, abstractmethod
from typing import Any

from fastapi import HTTPException, Request

from sdk.api_client.models import (
    {imports}
)


class AbstractEventHandler(ABC):
    \"\"\"
    Abstract Base Class that automatically handles parsing and routing
    incoming OpenAPI CloudEvents and unpacking their envelope,
    exposing the inner payload to their strongly-typed handler methods.
    \"\"\"

    async def dispatch_routing(self, request: Request) -> Any:
        try:
            payload = await request.json()
        except Exception:
            raise HTTPException(status_code=400, detail="Invalid JSON payload")

        event_type = payload.get("type")
        if not event_type:
            raise HTTPException(status_code=400, detail="Missing 'type' field in payload")

{dispatch_code}
        else:
            # Standard practice is to accept unhandled hooks with a 202/success to avoid webhook retries
            return {{"status": "ignored", "reason": f"No handler implemented for '{{event_type}}'"}}

{abstract_methods_code}
"""

    output_file = sdk_dir / "event_handler.py"
    output_file.write_text(base_class_content)
    print(f"✅ Generated base class successfully at: {output_file}")


if __name__ == "__main__":
    generate_event_handler_base()
