import ast
from pathlib import Path

TECHNICAL_ASSET_CONFIGURATION_DIR = (
    Path(__file__).parent.parent.parent
    / "backend"
    / "app"
    / "technical_asset_configuration"
)
PLUGINS_OUT_DIR = Path(__file__).parent.parent / "sdk" / "plugins"
KNOWN_ENUMS = {"AccessGranularity"}
HEADER = f"# CODE GENERATED BY {Path(__file__).name}. DO NOT EDIT MANUALLY.\n"


def _find_assignment(tree: ast.Module, name: str) -> str:
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.Assign)
            and len(node.targets) == 1
            and isinstance(node.targets[0], ast.Name)
            and node.targets[0].id == name
        ):
            return ast.literal_eval(node.value)
    raise ValueError(f"Could not find assignment to {name}")


def _plugin_class(tree: ast.Module) -> ast.ClassDef:
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and any(
            isinstance(base, ast.Name) and base.id == "TechnicalAssetPlugin"
            for base in node.bases
        ):
            return node
    raise ValueError("No TechnicalAssetPlugin subclass found")


def _has_configuration(plugin_class: ast.ClassDef) -> bool:
    return any(
        isinstance(node, ast.ClassDef) and node.name == "Meta"
        for node in plugin_class.body
    )


def _field_lines(plugin_class: ast.ClassDef, source: str) -> list[str]:
    """Copies each field's declaration verbatim, line for line, out of the
    backend plugin's own source."""
    source_lines = source.splitlines()
    fields = []
    for node in plugin_class.body:
        if not isinstance(node, ast.AnnAssign) or not isinstance(node.target, ast.Name):
            continue
        if node.target.id.startswith("_") or node.target.id in ("name", "version"):
            continue
        assert node.end_lineno is not None
        fields.append("\n".join(source_lines[node.lineno - 1 : node.end_lineno]))
    return fields


def build_plugin_module(plugin_dir: Path) -> tuple[str, str, str] | None:
    """Returns (module_name, class_name, source) for a plugin with its own
    configuration, or None for a plugin that has no configuration to expose."""
    schema_source = (plugin_dir / "schema.py").read_text()
    plugin_class = _plugin_class(ast.parse(schema_source))

    if not _has_configuration(plugin_class):
        return None

    configuration_type = _find_assignment(
        ast.parse((plugin_dir / "model.py").read_text()), "CONFIGURATION_TYPE"
    )
    fields = _field_lines(plugin_class, schema_source)
    used_enums = {enum for enum in KNOWN_ENUMS if any(enum in f for f in fields)}

    lines = ["from typing import ClassVar", ""]
    lines.append("from sdk.plugins.base import TechnicalAssetConfiguration")
    if used_enums:
        lines.append("from sdk.plugins.enums import " + ", ".join(sorted(used_enums)))
    lines.append("")
    lines.append("")
    lines.append(f"class {plugin_class.name}(TechnicalAssetConfiguration):")
    lines.append(f'    configuration_type: ClassVar[str] = "{configuration_type}"')
    lines.append("")
    lines.extend(fields)
    lines.append("")

    return (plugin_dir.name, plugin_class.name, "\n".join(lines))


def build_enums_module(used_enums: set[str]) -> str:
    source = (TECHNICAL_ASSET_CONFIGURATION_DIR / "enums.py").read_text()
    lines = ["from enum import Enum", ""]
    for node in ast.parse(source).body:
        if not isinstance(node, ast.ClassDef) or node.name not in used_enums:
            continue
        lines.append("")
        lines.append(f"class {node.name}(str, Enum):")
        for member in node.body:
            if isinstance(member, ast.Assign) and isinstance(
                member.targets[0], ast.Name
            ):
                value = ast.get_source_segment(source, member.value)
                lines.append(f"    {member.targets[0].id} = {value}")
    return "\n".join(lines) + "\n"


def main() -> None:
    PLUGINS_OUT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in PLUGINS_OUT_DIR.glob("*.py"):
        if stale.name not in ("base.py", "__init__.py"):
            stale.unlink()

    generated: list[tuple[str, str]] = []
    used_enums: set[str] = set()

    for plugin_dir in sorted(TECHNICAL_ASSET_CONFIGURATION_DIR.iterdir()):
        if not plugin_dir.is_dir() or not (plugin_dir / "schema.py").exists():
            continue
        result = build_plugin_module(plugin_dir)
        if result is None:
            continue
        module_name, class_name, source = result
        used_enums |= {enum for enum in KNOWN_ENUMS if enum in source}
        (PLUGINS_OUT_DIR / f"{module_name}.py").write_text(HEADER + source)
        generated.append((module_name, class_name))

    if used_enums:
        (PLUGINS_OUT_DIR / "enums.py").write_text(
            HEADER + build_enums_module(used_enums)
        )

    module_imports = {
        "base": "from sdk.plugins.base import TechnicalAssetConfiguration"
    }
    for module_name, class_name in generated:
        module_imports[module_name] = (
            f"from sdk.plugins.{module_name} import {class_name}"
        )
    if used_enums:
        module_imports["enums"] = "from sdk.plugins.enums import " + ", ".join(
            sorted(used_enums)
        )

    all_names = sorted(
        {class_name for _, class_name in generated}
        | {"TechnicalAssetConfiguration"}
        | used_enums
    )
    init_lines = [module_imports[name] for name in sorted(module_imports)]
    init_lines.append("")
    init_lines.append("__all__ = [")
    init_lines.extend(f'    "{name}",' for name in all_names)
    init_lines.append("]")

    (PLUGINS_OUT_DIR / "__init__.py").write_text(HEADER + "\n".join(init_lines) + "\n")


if __name__ == "__main__":
    main()
