// Code generated by oapi-codegen. DO NOT EDIT.

package portalsdk

import (
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type AccessGranularity string

const (
	AccessGranularitySchema AccessGranularity = "schema"
	AccessGranularityTable  AccessGranularity = "table"
)

// Validate checks if the AccessGranularity value is valid
func (a AccessGranularity) Validate() error {
	switch a {
	case AccessGranularitySchema, AccessGranularityTable:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid AccessGranularity value, got: %v", a))
	}
}

// AuthorizationAction The integer values for the authorization actions are stored directly in the DB.
// This means you can change the name of the actions, but not their integer values.
// The values for the actions are spaced on purpose, to make it easier to extend.
// This has no technical benefit, but it makes it easier to read for developers.
type AuthorizationAction int

const (
	AuthorizationActionN101 AuthorizationAction = 101
	AuthorizationActionN102 AuthorizationAction = 102
	AuthorizationActionN103 AuthorizationAction = 103
	AuthorizationActionN104 AuthorizationAction = 104
	AuthorizationActionN105 AuthorizationAction = 105
	AuthorizationActionN106 AuthorizationAction = 106
	AuthorizationActionN107 AuthorizationAction = 107
	AuthorizationActionN301 AuthorizationAction = 301
	AuthorizationActionN302 AuthorizationAction = 302
	AuthorizationActionN303 AuthorizationAction = 303
	AuthorizationActionN304 AuthorizationAction = 304
	AuthorizationActionN305 AuthorizationAction = 305
	AuthorizationActionN306 AuthorizationAction = 306
	AuthorizationActionN307 AuthorizationAction = 307
	AuthorizationActionN308 AuthorizationAction = 308
	AuthorizationActionN309 AuthorizationAction = 309
	AuthorizationActionN310 AuthorizationAction = 310
	AuthorizationActionN311 AuthorizationAction = 311
	AuthorizationActionN312 AuthorizationAction = 312
	AuthorizationActionN313 AuthorizationAction = 313
	AuthorizationActionN314 AuthorizationAction = 314
	AuthorizationActionN315 AuthorizationAction = 315
	AuthorizationActionN401 AuthorizationAction = 401
	AuthorizationActionN402 AuthorizationAction = 402
	AuthorizationActionN403 AuthorizationAction = 403
	AuthorizationActionN404 AuthorizationAction = 404
	AuthorizationActionN405 AuthorizationAction = 405
	AuthorizationActionN406 AuthorizationAction = 406
	AuthorizationActionN407 AuthorizationAction = 407
	AuthorizationActionN408 AuthorizationAction = 408
	AuthorizationActionN409 AuthorizationAction = 409
	AuthorizationActionN410 AuthorizationAction = 410
	AuthorizationActionN411 AuthorizationAction = 411
	AuthorizationActionN412 AuthorizationAction = 412
	AuthorizationActionN413 AuthorizationAction = 413
)

// Validate checks if the AuthorizationAction value is valid
func (a AuthorizationAction) Validate() error {
	switch a {
	case AuthorizationActionN101, AuthorizationActionN102, AuthorizationActionN103, AuthorizationActionN104, AuthorizationActionN105, AuthorizationActionN106, AuthorizationActionN107, AuthorizationActionN301, AuthorizationActionN302, AuthorizationActionN303, AuthorizationActionN304, AuthorizationActionN305, AuthorizationActionN306, AuthorizationActionN307, AuthorizationActionN308, AuthorizationActionN309, AuthorizationActionN310, AuthorizationActionN311, AuthorizationActionN312, AuthorizationActionN313, AuthorizationActionN314, AuthorizationActionN315, AuthorizationActionN401, AuthorizationActionN402, AuthorizationActionN403, AuthorizationActionN404, AuthorizationActionN405, AuthorizationActionN406, AuthorizationActionN407, AuthorizationActionN408, AuthorizationActionN409, AuthorizationActionN410, AuthorizationActionN411, AuthorizationActionN412, AuthorizationActionN413:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid AuthorizationAction value, got: %v", a))
	}
}

type DataProductIconKey string

const (
	DataProductIconKeyAnalytics       DataProductIconKey = "analytics"
	DataProductIconKeyDefault         DataProductIconKey = "default"
	DataProductIconKeyExploration     DataProductIconKey = "exploration"
	DataProductIconKeyIngestion       DataProductIconKey = "ingestion"
	DataProductIconKeyMachineLearning DataProductIconKey = "machine_learning"
	DataProductIconKeyProcessing      DataProductIconKey = "processing"
	DataProductIconKeyReporting       DataProductIconKey = "reporting"
)

// Validate checks if the DataProductIconKey value is valid
func (d DataProductIconKey) Validate() error {
	switch d {
	case DataProductIconKeyAnalytics, DataProductIconKeyDefault, DataProductIconKeyExploration, DataProductIconKeyIngestion, DataProductIconKeyMachineLearning, DataProductIconKeyProcessing, DataProductIconKeyReporting:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid DataProductIconKey value, got: %v", d))
	}
}

type DataProductSettingScope string

const (
	DataProductSettingScopeDataproduct DataProductSettingScope = "dataproduct"
	DataProductSettingScopeDataset     DataProductSettingScope = "dataset"
)

// Validate checks if the DataProductSettingScope value is valid
func (d DataProductSettingScope) Validate() error {
	switch d {
	case DataProductSettingScopeDataproduct, DataProductSettingScopeDataset:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid DataProductSettingScope value, got: %v", d))
	}
}

type DataProductSettingType string

const (
	DataProductSettingTypeCheckbox DataProductSettingType = "checkbox"
	DataProductSettingTypeInput    DataProductSettingType = "input"
	DataProductSettingTypeTags     DataProductSettingType = "tags"
)

// Validate checks if the DataProductSettingType value is valid
func (d DataProductSettingType) Validate() error {
	switch d {
	case DataProductSettingTypeCheckbox, DataProductSettingTypeInput, DataProductSettingTypeTags:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid DataProductSettingType value, got: %v", d))
	}
}

type DataProductStatus string

const (
	DataProductStatusActive   DataProductStatus = "active"
	DataProductStatusArchived DataProductStatus = "archived"
	DataProductStatusPending  DataProductStatus = "pending"
)

// Validate checks if the DataProductStatus value is valid
func (d DataProductStatus) Validate() error {
	switch d {
	case DataProductStatusActive, DataProductStatusArchived, DataProductStatusPending:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid DataProductStatus value, got: %v", d))
	}
}

type DecisionStatus string

const (
	DecisionStatusApproved DecisionStatus = "approved"
	DecisionStatusDenied   DecisionStatus = "denied"
	DecisionStatusPending  DecisionStatus = "pending"
)

// Validate checks if the DecisionStatus value is valid
func (d DecisionStatus) Validate() error {
	switch d {
	case DecisionStatusApproved, DecisionStatusDenied, DecisionStatusPending:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid DecisionStatus value, got: %v", d))
	}
}

type EventEntityType string

const (
	EventEntityTypeDataProduct    EventEntityType = "data_product"
	EventEntityTypeOutputPort     EventEntityType = "output_port"
	EventEntityTypeTechnicalAsset EventEntityType = "technical_asset"
	EventEntityTypeUser           EventEntityType = "user"
)

// Validate checks if the EventEntityType value is valid
func (e EventEntityType) Validate() error {
	switch e {
	case EventEntityTypeDataProduct, EventEntityTypeOutputPort, EventEntityTypeTechnicalAsset, EventEntityTypeUser:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid EventEntityType value, got: %v", e))
	}
}

type NodeType string

const (
	NodeTypeDataOutputNode  NodeType = "dataOutputNode"
	NodeTypeDataProductNode NodeType = "dataProductNode"
	NodeTypeDatasetNode     NodeType = "datasetNode"
	NodeTypeDomainNode      NodeType = "domainNode"
)

// Validate checks if the NodeType value is valid
func (n NodeType) Validate() error {
	switch n {
	case NodeTypeDataOutputNode, NodeTypeDataProductNode, NodeTypeDatasetNode, NodeTypeDomainNode:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid NodeType value, got: %v", n))
	}
}

type OutputPortAccessType string

const (
	OutputPortAccessTypePrivate    OutputPortAccessType = "private"
	OutputPortAccessTypePublic     OutputPortAccessType = "public"
	OutputPortAccessTypeRestricted OutputPortAccessType = "restricted"
)

// Validate checks if the OutputPortAccessType value is valid
func (o OutputPortAccessType) Validate() error {
	switch o {
	case OutputPortAccessTypePrivate, OutputPortAccessTypePublic, OutputPortAccessTypeRestricted:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid OutputPortAccessType value, got: %v", o))
	}
}

type OutputPortStatus string

const (
	OutputPortStatusActive   OutputPortStatus = "active"
	OutputPortStatusArchived OutputPortStatus = "archived"
	OutputPortStatusPending  OutputPortStatus = "pending"
)

// Validate checks if the OutputPortStatus value is valid
func (o OutputPortStatus) Validate() error {
	switch o {
	case OutputPortStatusActive, OutputPortStatusArchived, OutputPortStatusPending:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid OutputPortStatus value, got: %v", o))
	}
}

type Prototype int

const (
	PrototypeN0 Prototype = 0
	PrototypeN1 Prototype = 1
	PrototypeN2 Prototype = 2
	PrototypeN3 Prototype = 3
)

// Validate checks if the Prototype value is valid
func (p Prototype) Validate() error {
	switch p {
	case PrototypeN0, PrototypeN1, PrototypeN2, PrototypeN3:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid Prototype value, got: %v", p))
	}
}

type QueryStatsGranularity string

const (
	QueryStatsGranularityDay   QueryStatsGranularity = "day"
	QueryStatsGranularityMonth QueryStatsGranularity = "month"
	QueryStatsGranularityWeek  QueryStatsGranularity = "week"
)

// Validate checks if the QueryStatsGranularity value is valid
func (q QueryStatsGranularity) Validate() error {
	switch q {
	case QueryStatsGranularityDay, QueryStatsGranularityMonth, QueryStatsGranularityWeek:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid QueryStatsGranularity value, got: %v", q))
	}
}

type ResourceNameModel string

const (
	ResourceNameModelDataProduct        ResourceNameModel = "data_product"
	ResourceNameModelDataProductSetting ResourceNameModel = "data_product_setting"
	ResourceNameModelOutputPort         ResourceNameModel = "output_port"
	ResourceNameModelOutputPortSetting  ResourceNameModel = "output_port_setting"
	ResourceNameModelTechnicalAsset     ResourceNameModel = "technical_asset"
)

// Validate checks if the ResourceNameModel value is valid
func (r ResourceNameModel) Validate() error {
	switch r {
	case ResourceNameModelDataProduct, ResourceNameModelDataProductSetting, ResourceNameModelOutputPort, ResourceNameModelOutputPortSetting, ResourceNameModelTechnicalAsset:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid ResourceNameModel value, got: %v", r))
	}
}

type ResourceNameValidityType string

const (
	ResourceNameValidityTypeDUPLICATENAMESPACE ResourceNameValidityType = "DUPLICATE_NAMESPACE"
	ResourceNameValidityTypeINVALIDCHARACTERS  ResourceNameValidityType = "INVALID_CHARACTERS"
	ResourceNameValidityTypeINVALIDLENGTH      ResourceNameValidityType = "INVALID_LENGTH"
	ResourceNameValidityTypeVALID              ResourceNameValidityType = "VALID"
)

// Validate checks if the ResourceNameValidityType value is valid
func (r ResourceNameValidityType) Validate() error {
	switch r {
	case ResourceNameValidityTypeDUPLICATENAMESPACE, ResourceNameValidityTypeINVALIDCHARACTERS, ResourceNameValidityTypeINVALIDLENGTH, ResourceNameValidityTypeVALID:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid ResourceNameValidityType value, got: %v", r))
	}
}

type Scope string

const (
	ScopeDataProduct Scope = "data_product"
	ScopeDataset     Scope = "dataset"
	ScopeDomain      Scope = "domain"
	ScopeGlobal      Scope = "global"
)

// Validate checks if the Scope value is valid
func (s Scope) Validate() error {
	switch s {
	case ScopeDataProduct, ScopeDataset, ScopeDomain, ScopeGlobal:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid Scope value, got: %v", s))
	}
}

type TechnicalAssetStatus string

const (
	TechnicalAssetStatusActive   TechnicalAssetStatus = "active"
	TechnicalAssetStatusArchived TechnicalAssetStatus = "archived"
	TechnicalAssetStatusPending  TechnicalAssetStatus = "pending"
)

// Validate checks if the TechnicalAssetStatus value is valid
func (t TechnicalAssetStatus) Validate() error {
	switch t {
	case TechnicalAssetStatusActive, TechnicalAssetStatusArchived, TechnicalAssetStatusPending:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid TechnicalAssetStatus value, got: %v", t))
	}
}

type TechnicalMapping string

const (
	TechnicalMappingCustom  TechnicalMapping = "custom"
	TechnicalMappingDefault TechnicalMapping = "default"
)

// Validate checks if the TechnicalMapping value is valid
func (t TechnicalMapping) Validate() error {
	switch t {
	case TechnicalMappingCustom, TechnicalMappingDefault:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid TechnicalMapping value, got: %v", t))
	}
}

type UIElementType string

const (
	UIElementTypeCheckbox UIElementType = "checkbox"
	UIElementTypeRadio    UIElementType = "radio"
	UIElementTypeSelect   UIElementType = "select"
	UIElementTypeString   UIElementType = "string"
)

// Validate checks if the UIElementType value is valid
func (u UIElementType) Validate() error {
	switch u {
	case UIElementTypeCheckbox, UIElementTypeRadio, UIElementTypeSelect, UIElementTypeString:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid UIElementType value, got: %v", u))
	}
}
