// Code generated by oapi-codegen. DO NOT EDIT.

package portalsdk

type UpdateOutputPortQueryStatsBody = UpdateOutputPortQueryStatus

type DeleteOutputPortQueryStatBody = OutputPortQueryStatsDelete

type ReplaceOutputPortCuratedQueriesBody = OutputPortCuratedQueriesUpdate

type CreateOutputPortBody = CreateOutputPortRequest

type UpdateOutputPortBody = DatasetUpdate

type UpdateOutputPortAboutBody = DatasetAboutUpdate

type UpdateOutputPortStatusBody = DatasetStatusUpdate

type CreateDataProductBody = DataProductCreate

type UpdateDataProductBody = DataProductUpdate

type UpdateDataProductAboutBody = DataProductAboutUpdate

type UpdateDataProductStatusBody = DataProductStatusUpdate

type UpdateDataProductUsageBody = DataProductUsageUpdate

type LinkInputPortsToDataProductBody = LinkInputPortsToDataProduct

type CreateTechnicalAssetBody = CreateTechnicalAssetRequest

type UpdateDataProductTypeBody = DataProductTypeUpdate

type CreateDataProductTypeBody = DataProductTypeCreate

type CreateDataProductLifecycleBody = DataProductLifeCycleCreate

type UpdateDataProductLifecycleBody = DataProductLifeCycleUpdate

type CreateDataProductSettingBody = DataProductSettingCreate

type UpdateDataProductSettingBody = DataProductSettingUpdate

type ApproveOutputPortAsInputPortBody = ApproveOutputPortAsInputPortRequest

type DenyOutputPortAsInputPortBody = DenyOutputPortAsInputPortRequest

type RemoveOutputPortAsInputPortBody = RemoveOutputPortAsInputPortRequest

type ApproveOutputPortTechnicalAssetLinkBody = ApproveLinkBetweenTechnicalAssetAndOutputPortRequest

type DenyOutputPortTechnicalAssetLinkBody = DenyLinkBetweenTechnicalAssetAndOutputPortRequest

type LinkOutputPortToTechnicalAssetBody = LinkTechnicalAssetToOutputPortRequest

type UnlinkOutputPortFromTechnicalAssetBody = UnLinkTechnicalAssetToOutputPortRequest

type UpdateTechnicalAssetStatusBody = DataOutputStatusUpdate

type CreateDomainBody = DomainCreate

type UpdateDomainBody = DomainUpdate

type CreateTagBody = TagCreate

type UpdateTagBody = TagUpdate

type CreateUserBody = UserCreate

type SetCanBecomeAdminBody = CanBecomeAdminUpdate

type CreateRoleBody = CreateRole

type UpdateRoleBody = UpdateRole

type BecomeAdminBody = BecomeAdmin

type CreateGlobalRoleAssignmentBody = CreateGlobalRoleAssignment

type DecideGlobalRoleAssignmentBody = DecideGlobalRoleAssignment

type ModifyGlobalRoleAssignmentBody = ModifyGlobalRoleAssignment

type ModifyDataProductRoleAssignmentBody = ModifyDataProductRoleAssignment

type CreateDataProductRoleAssignmentBody = CreateDataProductRoleAssignment

type RequestDataProductRoleAssignmentBody = RequestDataProductRoleAssignment

type DecideDataProductRoleAssignmentBody = DecideDataProductRoleAssignment

type ModifyOutputPortRoleAssignmentBody = ModifyOutputPortRoleAssignment

type CreateOutputPortRoleAssignmentBody = CreateOutputPortRoleAssignment

type RequestOutputPortRoleAssignmentBody = RequestOutputPortRoleAssignment

type DecideOutputPortRoleAssignmentBody = DecideOutputPortRoleAssignment

type UpdateThemeSettingsBody = ThemeSettings

type ValidateResourceNameBody = ResourceNameValidationRequest
