apiVersion: v1
data:
  CORS_ALLOWED_ORIGINS: {{ .Values.host }}
  {{- if .Values.ai_agent.api_key }}
  AGENT_API_KEY: {{ .Values.ai_agent.api_key }}
  {{- end }}
kind: ConfigMap
metadata:
  name: {{ include "data-product-portal.agenticfullname" . }}
