apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-product-portal.fullname" . }}
data:
  POSTGRES_PASSWORD: {{ ternary .Values.global.postgresql.auth.password .Values.database.password .Values.postgres_enabled | quote }}
  OIDC_CLIENT_ID: {{ .Values.oidc.client_id }}
  OIDC_CLIENT_SECRET: {{ .Values.oidc.client_secret }}
  CONVEYOR_API_KEY: {{ .Values.conveyor.api_key }}
  CONVEYOR_SECRET: {{ .Values.conveyor.secret }}
  {{- if .Values.api_key.enabled }}
  PORTAL_API_KEY: {{ .Values.api_key.key }}
  {{- end }}
  SMTP_USERNAME: {{ .Values.smtp.username }}
  SMTP_PASSWORD: {{ .Values.smtp.password }}
  {{- if .Values.webhook.secret }}
  WEBHOOK_SECRET: {{ .Values.webhook.secret }}
  {{- end }}
