apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-product-portal.fullname" . }}
data:
  POSTGRES_PASSWORD: {{ ternary .Values.global.postgresql.auth.password .Values.database.password .Values.postgres_enabled | b64enc | quote }}
  OIDC_CLIENT_ID: {{ .Values.oidc.client_id | b64enc | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.oidc.client_secret | b64enc | quote }}
  CONVEYOR_API_KEY: {{ .Values.conveyor.api_key | b64enc | quote }}
  CONVEYOR_SECRET: {{ .Values.conveyor.secret | b64enc | quote }}
  {{- if .Values.api_key.enabled }}
  PORTAL_API_KEY: {{ .Values.api_key.key | b64enc | quote }}
  {{- end }}
  SMTP_USERNAME: {{ .Values.smtp.username | b64enc | quote }}
  SMTP_PASSWORD: {{ .Values.smtp.password | b64enc | quote }}
  {{- if .Values.webhook.secret }}
  WEBHOOK_SECRET: {{ .Values.webhook.secret | b64enc | quote }}
  {{- end }}
