logistics_wms_shipments:
  outputs:
    dev:
      dbname: dpp_demo
      host: localhost
      pass: abc123
      port: 5433
      schema: logistics_wms_shipments
      threads: 1
      type: postgres
      user: postgres
  target: dev
