raw_test:
  s3:
    - bucket_name: datalake
      path: /raw/test
  owner: ["test-project-1"]

clean_test:
  glue:
    - clean_test/*
  owner: ["test-project-1"]

master_test:
  glue:
    - master_test/table1
    - master_test/table2
  owner: ["test-project-2"]
