raw_test:
  s3:
    - bucket_name: datalake
      path: /raw/test
  owner: ["test-project-1"]

clean_test:
  glue:
    - clean_test/*
  owner: ["test-project-1"]

master_test:
  glue:
    - master_test/table1
    - master_test/table2
  owner: ["test-project-2"]

raw_gemeente_verslagen:
  s3:
    - bucket_name: datalake
      path: /raw/gemeente_verslagen
  owner: ["verslag-ingest", "verslag-text-extraction"]

raw_themas:
  s3:
    - bucket_name: datalake
      path: /raw/themas
  owner: ["verslag-ingest", "verslag-text-extraction"]

clean_gemeente_verslagen:
  s3:
    - bucket_name: datalake
      path: /clean/gemeente_verslagen
  owner: ["verslag-text-extraction"]

clean_themas:
  s3:
    - bucket_name: datalake
      path: /clean/themas
  owner: ["verslag-text-extraction"]

master_gemeente_verslagen:
  glue:
    - master_gemeente_verslagen/*
  owner: ["verslag-analytics", "verslag-text-extraction"]
