raw_test:
  s3:
    bucket: datalake
    suffix: /raw/test
    path: ''
  owner: test-project-1

clean_test:
  glue:
    database: clean_test
    database_suffix: suffix
    table: '*'
    bucket_identifier: datalake
    database_path: clean/test/suffix
    table_path: ''
  owner: test-project-1

master_test_table1:
  glue:
    database: master_test
    database_suffix: ''
    table: table1
    bucket_identifier: datalake
    database_path: master/test
    table_path: table1
  owner: test-project-2

master_test_table2:
  glue:
    database: master_test
    database_suffix: ''
    table: table2
    bucket_identifier: datalake
    database_path: master/test
    table_path: something_other_than_table2
  owner: test-project-2

dbx_output_schema:
  databricks:
    schema: schema
    schema_suffix: suffix
    bucket_identifier: datalake
    schema_path: data_product/test-project-2/schema/suffix
  owner: test-project-2
