version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - errcheck
    - exhaustive
    - gocritic
    - godot
    - govet
    - ineffassign
    - makezero
    - misspell
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unused
    - wastedassign
    - whitespace
  settings:
    exhaustive:
      default-signifies-exhaustive: false
    gocritic:
      disabled-checks:
        - commentFormatting
    revive:
      rules:
        - name: defer
          arguments:
            - - call-chain
              - loop
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(portal)
    goimports:
      local-prefixes:
        - portal
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
