name: "Bug report \U0001F41E"
description: Create a bug report
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Found in version
      description: The portal version where you found the bug, shown at the bottom of the sidebar.
      placeholder: e.g. 0.7.4
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        - OS: [e.g. Arch Linux]
        - Other details that you think may affect.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
