{{ cookiecutter.project_slug }}:
  outputs:
    dev:
      dbname: dpp_demo
      host: localhost
      pass: abc123
      port: 5433
      schema: {{ cookiecutter.project_slug }}
      threads: 1
      type: postgres
      user: postgres
  target: dev
