import json
import uuid
from typing import Any, Optional
from unittest.mock import AsyncMock, patch

import faker
import pytest
from fastapi import Request
from fastapi.datastructures import Headers
from sdk.api_client.models import ExplorationEvent
from sdk.provisioner.event_handler import EmptyEventHandler

from app.authorization.roles.schema import Scope
from app.core.authz import Action
from app.settings import settings
from tests.factories import (
    DataProductTypeFactory,
    DomainFactory,
    GlobalRoleAssignmentFactory,
    LifecycleFactory,
    RoleFactory,
    TagFactory,
    UserFactory,
)

ENDPOINT = "/api/v2/explorations"


@pytest.fixture
def user_with_create_exploration_rights():
    user = UserFactory(external_id=settings.DEFAULT_USERNAME)
    role = RoleFactory(
        scope=Scope.GLOBAL,
        permissions=[Action.GLOBAL__CREATE_EXPLORATION],
    )
    GlobalRoleAssignmentFactory(
        user_id=user.id,
        role_id=role.id,
    )
    return user


@pytest.fixture
def payload() -> dict[str, Any]:
    domain = DomainFactory()
    lifecycle = LifecycleFactory()
    data_product_type = DataProductTypeFactory()
    user = UserFactory()
    tag = TagFactory()
    return {
        "name": str(uuid.uuid4()),
        "description": "Updated Data Product Description",
        "namespace": str(uuid.uuid4()),
        "tag_ids": [str(tag.id)],
        "type_id": str(data_product_type.id),
        "owners": [str(user.id)],
        "lifecycle_id": str(lifecycle.id),
        "domain_id": str(domain.id),
    }


# 1. Create a Spy Handler using your generated SDK base class
class WebhookSpy(EmptyEventHandler):
    def __init__(self):
        self.captured_payload: Optional[ExplorationEvent] = None

    # This method name matches the convention generated by your SDK script
    async def on_exploration_event(self, data: ExplorationEvent) -> dict[str, str]:
        self.captured_payload = data
        return {"status": "success"}


class TestSDKWebhookIntegration:
    def test_sdk_handler_receives_and_parses_generated_cloudevent(
        self,
        client,
        user_with_create_exploration_rights,
        monkeypatch,
    ):
        spy = WebhookSpy()

        monkeypatch.setattr(
            settings, "WEBHOOK_V2_URL", "http://sdk-receiver.local/webhook"
        )

        async def intercept_webhook_delivery(event_type: str, data: dict) -> None:
            import uuid
            from datetime import datetime, timezone

            cloudevent_envelope = {
                "specversion": "1.0",
                "id": str(uuid.uuid4()),
                "source": "data-product-portal",
                "type": event_type,
                "time": datetime.now(timezone.utc).isoformat(),
                "data": data,
            }

            async def mock_receive():
                return {
                    "type": "http.request",
                    "body": json.dumps(cloudevent_envelope).encode(),
                    "more_body": False,
                }

            nested_request = Request(
                scope={
                    "type": "http",
                    "method": "POST",
                    "path": "/webhook",
                    "headers": Headers().raw,
                },
                receive=mock_receive,
            )

            await spy.dispatch_routing(nested_request)

        mock_call = AsyncMock(side_effect=intercept_webhook_delivery)
        patch("app.main.call_v2_webhook", new=mock_call).start()
        d = DomainFactory()
        payload = {
            "name": str(uuid.uuid4()),
            "namespace": str(uuid.uuid4()),
            "domain_id": str(d.id),
            "description": faker.Faker().text(),
        }

        response = client.post(ENDPOINT, json=payload)
        assert response.status_code == 200
        assert spy.captured_payload is not None
        assert response.json()["id"] == str(spy.captured_payload.id)

        patch.stopall()

    @pytest.mark.asyncio
    async def test_sdk_handler_gracefully_ignores_unrecognized_event_types(self):
        handler = EmptyEventHandler()

        rogue_envelope = {
            "specversion": "1.0",
            "id": "12345",
            "source": "data-product-portal",
            "type": "galaxy.destroyed",  # Unrecognized type
            "time": "2026-06-08T00:00:00Z",
            "data": {"extinction_level": "high"},
        }

        async def mock_receive():
            return {
                "type": "http.request",
                "body": json.dumps(rogue_envelope).encode(),
                "more_body": False,
            }

        nested_request = Request(
            scope={
                "type": "http",
                "method": "POST",
                "path": "/webhook",
                "headers": Headers().raw,
            },
            receive=mock_receive,
        )

        result = await handler.dispatch_routing(nested_request)
        assert result["status"] == "ignored"
        assert "galaxy.destroyed" in result["reason"]
