# CODE GENERATED BY build_plugin_configurations.py. DO NOT EDIT MANUALLY.
from sdk.plugins.azure_blob import AzureBlobTechnicalAssetConfiguration
from sdk.plugins.base import TechnicalAssetConfiguration
from sdk.plugins.databricks import DatabricksTechnicalAssetConfiguration
from sdk.plugins.enums import AccessGranularity
from sdk.plugins.glue import GlueTechnicalAssetConfiguration
from sdk.plugins.osi_sem_model import OSISemanticModelTechnicalAssetConfiguration
from sdk.plugins.postgresql import PostgreSQLTechnicalAssetConfiguration
from sdk.plugins.redshift import RedshiftTechnicalAssetConfiguration
from sdk.plugins.rustfs import RustFSTechnicalAssetConfiguration
from sdk.plugins.s3 import S3TechnicalAssetConfiguration
from sdk.plugins.snowflake import SnowflakeTechnicalAssetConfiguration

__all__ = [
    "AccessGranularity",
    "AzureBlobTechnicalAssetConfiguration",
    "DatabricksTechnicalAssetConfiguration",
    "GlueTechnicalAssetConfiguration",
    "OSISemanticModelTechnicalAssetConfiguration",
    "PostgreSQLTechnicalAssetConfiguration",
    "RedshiftTechnicalAssetConfiguration",
    "RustFSTechnicalAssetConfiguration",
    "S3TechnicalAssetConfiguration",
    "SnowflakeTechnicalAssetConfiguration",
    "TechnicalAssetConfiguration",
]
