# CODE GENERATED BY build_plugin_configurations.py. DO NOT EDIT MANUALLY.
from typing import ClassVar

from sdk.plugins.base import TechnicalAssetConfiguration


class AzureBlobTechnicalAssetConfiguration(TechnicalAssetConfiguration):
    name: ClassVar[str] = "AzureBlobTechnicalAssetConfiguration"

    domain: str = ""
    path: str = ""
    container_name: str
