# CODE GENERATED BY build_plugin_configurations.py. DO NOT EDIT MANUALLY.
from typing import ClassVar

from sdk.plugins.base import TechnicalAssetConfiguration
from sdk.plugins.enums import AccessGranularity


class GlueTechnicalAssetConfiguration(TechnicalAssetConfiguration):
    name: ClassVar[str] = "GlueTechnicalAssetConfiguration"

    database: str
    database_suffix: str = ""
    table: str = "*"
    bucket_identifier: str = ""
    database_path: str = ""
    table_path: str = ""
    access_granularity: AccessGranularity
