# CODE GENERATED BY build_plugin_configurations.py. DO NOT EDIT MANUALLY.
from typing import ClassVar

from sdk.plugins.base import TechnicalAssetConfiguration


class OSISemanticModelTechnicalAssetConfiguration(TechnicalAssetConfiguration):
    name: ClassVar[str] = "OSISemanticModelTechnicalAssetConfiguration"

    model_name: str = ""
    location: str = ""
