# CODE GENERATED BY build_plugin_configurations.py. DO NOT EDIT MANUALLY.
from typing import ClassVar

from sdk.plugins.base import TechnicalAssetConfiguration


class ParameterStoreTechnicalAssetConfiguration(TechnicalAssetConfiguration):
    name: ClassVar[str] = "ParameterStoreTechnicalAssetConfiguration"

    prefix: str = ""
    parameter_name: str
