# CODE GENERATED BY build_plugin_configurations.py. DO NOT EDIT MANUALLY.
from typing import ClassVar

from sdk.plugins.base import TechnicalAssetConfiguration
from sdk.plugins.enums import AccessGranularity


class PostgreSQLTechnicalAssetConfiguration(TechnicalAssetConfiguration):
    name: ClassVar[str] = "PostgreSQLTechnicalAssetConfiguration"

    database: str
    schema: str = ""
    table: str = "*"
    access_granularity: AccessGranularity
