# CODE GENERATED BY build_plugin_configurations.py. DO NOT EDIT MANUALLY.
from typing import ClassVar

from sdk.plugins.base import TechnicalAssetConfiguration
from sdk.plugins.enums import AccessGranularity


class RedshiftTechnicalAssetConfiguration(TechnicalAssetConfiguration):
    configuration_type: ClassVar[str] = "RedshiftTechnicalAssetConfiguration"

    database: str
    schema: str = ""
    table: str = "*"
    bucket_identifier: str = ""
    database_path: str = ""
    table_path: str = ""
    access_granularity: AccessGranularity
