# CODE GENERATED BY build_plugin_configurations.py. DO NOT EDIT MANUALLY.
from typing import ClassVar

from sdk.plugins.base import TechnicalAssetConfiguration


class RustFSTechnicalAssetConfiguration(TechnicalAssetConfiguration):
    configuration_type: ClassVar[str] = "RustFSTechnicalAssetConfiguration"

    bucket: str
    suffix: str = ""
    path: str
