# CODE GENERATED BY build_plugin_configurations.py. DO NOT EDIT MANUALLY.
from typing import ClassVar

from sdk.plugins.base import TechnicalAssetConfiguration


class S3TechnicalAssetConfiguration(TechnicalAssetConfiguration):
    configuration_type: ClassVar[str] = "S3TechnicalAssetConfiguration"

    bucket: str
    suffix: str = ""
    path: str
