# CODE GENERATED BY build_event_handler.py. DO NOT EDIT MANUALLY.
from abc import ABC, abstractmethod
from typing import Any
from fastapi import Request, HTTPException

from sdk.api_client.models import (
    CloudEventDataProductAboutUpdatedEvent,
    CloudEventDataProductCreatedEvent,
    CloudEventDataProductDeletedEvent,
    CloudEventDataProductInputPortLinkedEvent,
    CloudEventDataProductInputPortUnlinkedEvent,
    CloudEventDataProductSettingChangedEvent,
    CloudEventDataProductStatusUpdatedEvent,
    CloudEventDataProductTeamMemberAddedEvent,
    CloudEventDataProductTeamMemberRemovedEvent,
    CloudEventDataProductTeamMemberUpdatedEvent,
    CloudEventDataProductUpdatedEvent,
    CloudEventOutputPortAboutUpdatedEvent,
    CloudEventOutputPortCreatedEvent,
    CloudEventOutputPortDeletedEvent,
    CloudEventOutputPortLinkApprovedEvent,
    CloudEventOutputPortLinkDeniedEvent,
    CloudEventOutputPortSettingChangedEvent,
    CloudEventOutputPortStatusUpdatedEvent,
    CloudEventOutputPortUpdatedEvent,
    CloudEventTechnicalAssetCreatedEvent,
    CloudEventTechnicalAssetDeletedEvent,
    CloudEventTechnicalAssetLinkApprovedEvent,
    CloudEventTechnicalAssetLinkDeniedEvent,
    CloudEventTechnicalAssetLinkedEvent,
    CloudEventTechnicalAssetStatusUpdatedEvent,
    CloudEventTechnicalAssetUnlinkedEvent,
    CloudEventTechnicalAssetUpdatedEvent,
    DataProductAboutUpdatedEvent,
    DataProductCreatedEvent,
    DataProductDeletedEvent,
    DataProductInputPortLinkedEvent,
    DataProductInputPortUnlinkedEvent,
    DataProductSettingChangedEvent,
    DataProductStatusUpdatedEvent,
    DataProductTeamMemberAddedEvent,
    DataProductTeamMemberRemovedEvent,
    DataProductTeamMemberUpdatedEvent,
    DataProductUpdatedEvent,
    OutputPortAboutUpdatedEvent,
    OutputPortCreatedEvent,
    OutputPortDeletedEvent,
    OutputPortLinkApprovedEvent,
    OutputPortLinkDeniedEvent,
    OutputPortSettingChangedEvent,
    OutputPortStatusUpdatedEvent,
    OutputPortUpdatedEvent,
    TechnicalAssetCreatedEvent,
    TechnicalAssetDeletedEvent,
    TechnicalAssetLinkApprovedEvent,
    TechnicalAssetLinkDeniedEvent,
    TechnicalAssetLinkedEvent,
    TechnicalAssetStatusUpdatedEvent,
    TechnicalAssetUnlinkedEvent,
    TechnicalAssetUpdatedEvent
)

class AbstractEventHandler(ABC):
    """
    Abstract Base Class that automatically handles parsing and routing 
    incoming OpenAPI CloudEvents and unpacking their envelope,
    exposing the inner payload to their strongly-typed handler methods.
    """

    async def dispatch_routing(self, request: Request) -> Any:
        try:
            payload = await request.json()
        except Exception:
            raise HTTPException(status_code=400, detail="Invalid JSON payload")

        event_type = payload.get("type")
        if not event_type:
            raise HTTPException(status_code=400, detail="Missing 'type' field in payload")

        if event_type == "data_product.team_member_updated":
            parsed_event = CloudEventDataProductTeamMemberUpdatedEvent.from_dict(payload)
            return await self.on_data_product_team_member_updated(parsed_event.data)
        elif event_type == "technical_asset.created":
            parsed_event = CloudEventTechnicalAssetCreatedEvent.from_dict(payload)
            return await self.on_technical_asset_created(parsed_event.data)
        elif event_type == "data_product.team_member_removed":
            parsed_event = CloudEventDataProductTeamMemberRemovedEvent.from_dict(payload)
            return await self.on_data_product_team_member_removed(parsed_event.data)
        elif event_type == "technical_asset.unlinked":
            parsed_event = CloudEventTechnicalAssetUnlinkedEvent.from_dict(payload)
            return await self.on_technical_asset_unlinked(parsed_event.data)
        elif event_type == "data_product.input_port_unlinked":
            parsed_event = CloudEventDataProductInputPortUnlinkedEvent.from_dict(payload)
            return await self.on_data_product_input_port_unlinked(parsed_event.data)
        elif event_type == "output_port.setting_changed":
            parsed_event = CloudEventOutputPortSettingChangedEvent.from_dict(payload)
            return await self.on_output_port_setting_changed(parsed_event.data)
        elif event_type == "output_port.created":
            parsed_event = CloudEventOutputPortCreatedEvent.from_dict(payload)
            return await self.on_output_port_created(parsed_event.data)
        elif event_type == "output_port.status_updated":
            parsed_event = CloudEventOutputPortStatusUpdatedEvent.from_dict(payload)
            return await self.on_output_port_status_updated(parsed_event.data)
        elif event_type == "data_product.team_member_added":
            parsed_event = CloudEventDataProductTeamMemberAddedEvent.from_dict(payload)
            return await self.on_data_product_team_member_added(parsed_event.data)
        elif event_type == "technical_asset.linked":
            parsed_event = CloudEventTechnicalAssetLinkedEvent.from_dict(payload)
            return await self.on_technical_asset_linked(parsed_event.data)
        elif event_type == "output_port.updated":
            parsed_event = CloudEventOutputPortUpdatedEvent.from_dict(payload)
            return await self.on_output_port_updated(parsed_event.data)
        elif event_type == "technical_asset.updated":
            parsed_event = CloudEventTechnicalAssetUpdatedEvent.from_dict(payload)
            return await self.on_technical_asset_updated(parsed_event.data)
        elif event_type == "data_product.deleted":
            parsed_event = CloudEventDataProductDeletedEvent.from_dict(payload)
            return await self.on_data_product_deleted(parsed_event.data)
        elif event_type == "data_product.setting_changed":
            parsed_event = CloudEventDataProductSettingChangedEvent.from_dict(payload)
            return await self.on_data_product_setting_changed(parsed_event.data)
        elif event_type == "output_port.link_approved":
            parsed_event = CloudEventOutputPortLinkApprovedEvent.from_dict(payload)
            return await self.on_output_port_link_approved(parsed_event.data)
        elif event_type == "data_product.status_updated":
            parsed_event = CloudEventDataProductStatusUpdatedEvent.from_dict(payload)
            return await self.on_data_product_status_updated(parsed_event.data)
        elif event_type == "data_product.created":
            parsed_event = CloudEventDataProductCreatedEvent.from_dict(payload)
            return await self.on_data_product_created(parsed_event.data)
        elif event_type == "data_product.about_updated":
            parsed_event = CloudEventDataProductAboutUpdatedEvent.from_dict(payload)
            return await self.on_data_product_about_updated(parsed_event.data)
        elif event_type == "technical_asset.link_denied":
            parsed_event = CloudEventTechnicalAssetLinkDeniedEvent.from_dict(payload)
            return await self.on_technical_asset_link_denied(parsed_event.data)
        elif event_type == "output_port.deleted":
            parsed_event = CloudEventOutputPortDeletedEvent.from_dict(payload)
            return await self.on_output_port_deleted(parsed_event.data)
        elif event_type == "data_product.input_port_linked":
            parsed_event = CloudEventDataProductInputPortLinkedEvent.from_dict(payload)
            return await self.on_data_product_input_port_linked(parsed_event.data)
        elif event_type == "technical_asset.link_approved":
            parsed_event = CloudEventTechnicalAssetLinkApprovedEvent.from_dict(payload)
            return await self.on_technical_asset_link_approved(parsed_event.data)
        elif event_type == "technical_asset.status_updated":
            parsed_event = CloudEventTechnicalAssetStatusUpdatedEvent.from_dict(payload)
            return await self.on_technical_asset_status_updated(parsed_event.data)
        elif event_type == "data_product.updated":
            parsed_event = CloudEventDataProductUpdatedEvent.from_dict(payload)
            return await self.on_data_product_updated(parsed_event.data)
        elif event_type == "output_port.about_updated":
            parsed_event = CloudEventOutputPortAboutUpdatedEvent.from_dict(payload)
            return await self.on_output_port_about_updated(parsed_event.data)
        elif event_type == "technical_asset.deleted":
            parsed_event = CloudEventTechnicalAssetDeletedEvent.from_dict(payload)
            return await self.on_technical_asset_deleted(parsed_event.data)
        elif event_type == "output_port.link_denied":
            parsed_event = CloudEventOutputPortLinkDeniedEvent.from_dict(payload)
            return await self.on_output_port_link_denied(parsed_event.data)
        else:
            # Standard practice is to accept unhandled hooks with a 202/success to avoid webhook retries
            return {"status": "ignored", "reason": f"No handler implemented for '{event_type}'"}

    @abstractmethod
    async def on_data_product_team_member_updated(self, data: DataProductTeamMemberUpdatedEvent) -> Any:
        """Handler for the parsed payload of 'data_product.team_member_updated' """
        pass

    @abstractmethod
    async def on_technical_asset_created(self, data: TechnicalAssetCreatedEvent) -> Any:
        """Handler for the parsed payload of 'technical_asset.created' """
        pass

    @abstractmethod
    async def on_data_product_team_member_removed(self, data: DataProductTeamMemberRemovedEvent) -> Any:
        """Handler for the parsed payload of 'data_product.team_member_removed' """
        pass

    @abstractmethod
    async def on_technical_asset_unlinked(self, data: TechnicalAssetUnlinkedEvent) -> Any:
        """Handler for the parsed payload of 'technical_asset.unlinked' """
        pass

    @abstractmethod
    async def on_data_product_input_port_unlinked(self, data: DataProductInputPortUnlinkedEvent) -> Any:
        """Handler for the parsed payload of 'data_product.input_port_unlinked' """
        pass

    @abstractmethod
    async def on_output_port_setting_changed(self, data: OutputPortSettingChangedEvent) -> Any:
        """Handler for the parsed payload of 'output_port.setting_changed' """
        pass

    @abstractmethod
    async def on_output_port_created(self, data: OutputPortCreatedEvent) -> Any:
        """Handler for the parsed payload of 'output_port.created' """
        pass

    @abstractmethod
    async def on_output_port_status_updated(self, data: OutputPortStatusUpdatedEvent) -> Any:
        """Handler for the parsed payload of 'output_port.status_updated' """
        pass

    @abstractmethod
    async def on_data_product_team_member_added(self, data: DataProductTeamMemberAddedEvent) -> Any:
        """Handler for the parsed payload of 'data_product.team_member_added' """
        pass

    @abstractmethod
    async def on_technical_asset_linked(self, data: TechnicalAssetLinkedEvent) -> Any:
        """Handler for the parsed payload of 'technical_asset.linked' """
        pass

    @abstractmethod
    async def on_output_port_updated(self, data: OutputPortUpdatedEvent) -> Any:
        """Handler for the parsed payload of 'output_port.updated' """
        pass

    @abstractmethod
    async def on_technical_asset_updated(self, data: TechnicalAssetUpdatedEvent) -> Any:
        """Handler for the parsed payload of 'technical_asset.updated' """
        pass

    @abstractmethod
    async def on_data_product_deleted(self, data: DataProductDeletedEvent) -> Any:
        """Handler for the parsed payload of 'data_product.deleted' """
        pass

    @abstractmethod
    async def on_data_product_setting_changed(self, data: DataProductSettingChangedEvent) -> Any:
        """Handler for the parsed payload of 'data_product.setting_changed' """
        pass

    @abstractmethod
    async def on_output_port_link_approved(self, data: OutputPortLinkApprovedEvent) -> Any:
        """Handler for the parsed payload of 'output_port.link_approved' """
        pass

    @abstractmethod
    async def on_data_product_status_updated(self, data: DataProductStatusUpdatedEvent) -> Any:
        """Handler for the parsed payload of 'data_product.status_updated' """
        pass

    @abstractmethod
    async def on_data_product_created(self, data: DataProductCreatedEvent) -> Any:
        """Handler for the parsed payload of 'data_product.created' """
        pass

    @abstractmethod
    async def on_data_product_about_updated(self, data: DataProductAboutUpdatedEvent) -> Any:
        """Handler for the parsed payload of 'data_product.about_updated' """
        pass

    @abstractmethod
    async def on_technical_asset_link_denied(self, data: TechnicalAssetLinkDeniedEvent) -> Any:
        """Handler for the parsed payload of 'technical_asset.link_denied' """
        pass

    @abstractmethod
    async def on_output_port_deleted(self, data: OutputPortDeletedEvent) -> Any:
        """Handler for the parsed payload of 'output_port.deleted' """
        pass

    @abstractmethod
    async def on_data_product_input_port_linked(self, data: DataProductInputPortLinkedEvent) -> Any:
        """Handler for the parsed payload of 'data_product.input_port_linked' """
        pass

    @abstractmethod
    async def on_technical_asset_link_approved(self, data: TechnicalAssetLinkApprovedEvent) -> Any:
        """Handler for the parsed payload of 'technical_asset.link_approved' """
        pass

    @abstractmethod
    async def on_technical_asset_status_updated(self, data: TechnicalAssetStatusUpdatedEvent) -> Any:
        """Handler for the parsed payload of 'technical_asset.status_updated' """
        pass

    @abstractmethod
    async def on_data_product_updated(self, data: DataProductUpdatedEvent) -> Any:
        """Handler for the parsed payload of 'data_product.updated' """
        pass

    @abstractmethod
    async def on_output_port_about_updated(self, data: OutputPortAboutUpdatedEvent) -> Any:
        """Handler for the parsed payload of 'output_port.about_updated' """
        pass

    @abstractmethod
    async def on_technical_asset_deleted(self, data: TechnicalAssetDeletedEvent) -> Any:
        """Handler for the parsed payload of 'technical_asset.deleted' """
        pass

    @abstractmethod
    async def on_output_port_link_denied(self, data: OutputPortLinkDeniedEvent) -> Any:
        """Handler for the parsed payload of 'output_port.link_denied' """
        pass
