# CODE GENERATED BY build_event_handler.py. DO NOT EDIT MANUALLY.
from abc import ABC, abstractmethod
from typing import Any

from fastapi import HTTPException, Request

from sdk.api_client.models import (
    CloudEventDataProductEvent,
    CloudEventExplorationEvent,
    CloudEventInputPortEvent,
    DataProductEvent,
    ExplorationEvent,
    InputPortEvent,
)


class AbstractEventHandler(ABC):
    """
    Abstract Base Class that automatically handles parsing and routing
    incoming OpenAPI CloudEvents and unpacking their envelope,
    exposing the inner payload to their strongly-typed handler methods.
    """

    async def dispatch_routing(self, request: Request) -> Any:
        try:
            payload = await request.json()
        except Exception:
            raise HTTPException(status_code=400, detail="Invalid JSON payload")

        event_type = payload.get("type")
        if not event_type:
            raise HTTPException(
                status_code=400, detail="Missing 'type' field in payload"
            )

        parsed_event: Any
        if event_type == "data_product.event":
            parsed_event = CloudEventDataProductEvent.from_dict(payload)
            return await self.on_data_product_event(parsed_event.data)
        elif event_type == "exploration.event":
            parsed_event = CloudEventExplorationEvent.from_dict(payload)
            return await self.on_exploration_event(parsed_event.data)
        elif event_type == "input_port.event":
            parsed_event = CloudEventInputPortEvent.from_dict(payload)
            return await self.on_input_port_event(parsed_event.data)
        else:
            # Standard practice is to accept unhandled hooks with a 202/success to avoid webhook retries
            return {
                "status": "ignored",
                "reason": f"No handler implemented for '{event_type}'",
            }

    @abstractmethod
    async def on_data_product_event(self, data: DataProductEvent) -> Any:
        """Handler for the parsed payload of 'data_product.event'"""
        pass

    @abstractmethod
    async def on_exploration_event(self, data: ExplorationEvent) -> Any:
        """Handler for the parsed payload of 'exploration.event'"""
        pass

    @abstractmethod
    async def on_input_port_event(self, data: InputPortEvent) -> Any:
        """Handler for the parsed payload of 'input_port.event'"""
        pass


class EmptyEventHandler(AbstractEventHandler):
    """
    An empty implementation of AbstractEventHandler for testing purposes.
    Inherit from this in your tests to avoid implementing every single abstract method.
    """

    async def on_data_product_event(self, data: DataProductEvent) -> Any:
        pass

    async def on_exploration_event(self, data: ExplorationEvent) -> Any:
        pass

    async def on_input_port_event(self, data: InputPortEvent) -> Any:
        pass
