"""Generate webhook-events.md by introspecting the FastAPI app.

Usage:
    cd backend && poetry run python -m app.webhook_doc_export

Run this after modifying v2 event emissions in any router, then commit the output.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

import typer
from fastapi.routing import APIRoute

if TYPE_CHECKING:
    from fastapi import FastAPI

API_DOCS_BASE = "/docs/api/#schema"

GROUPS: dict[str, str] = {
    "data_product": "Data Product Events",
    "output_port": "Output Port Events",
    "technical_asset": "Technical Asset Events",
}

HEADER = """\
---
title: Webhook Events (v2)
description: Reference for all v2 webhook events emitted by the Data Product Portal
sidebar_position: 9
---

{/* Auto-generated by backend/app/webhook_doc_export.py — do not edit manually */}

:::note
This is a alpha feature, and we expect message envelopes to still evolve over time.
:::

The Data Product Portal emits webhook events following the [CloudEvents](https://cloudevents.io/) specification.
All events are delivered as HTTP POST requests to the configured endpoint.

## Configuration

Set the `WEBHOOK_V2_URL` environment variable to receive events.
When not set, no events are emitted.

## Envelope

Every event is wrapped in a CloudEvents envelope:

```json
{
  "specversion": "1.0",
  "id": "<uuid>",
  "source": "data-product-portal",
  "type": "data_product.created",
  "time": "2026-04-18T12:00:00Z",
  "data": { ... }
}
```

## Events

"""


def build_event_list(app: FastAPI) -> list[dict]:
    """Walk app routes and collect events from webhook-emitting dependencies."""
    events: list[dict] = []
    seen: set[tuple] = set()

    for route in app.routes:
        if not isinstance(route, APIRoute):
            continue
        for dep in route.dependencies:
            fn = dep.dependency
            if not hasattr(fn, "_webhook_event_type"):
                continue
            event_type: str = fn._webhook_event_type
            event_model = fn._webhook_payload_model
            method = sorted(route.methods)[0]
            key = (event_type, method, route.path)
            if key in seen:
                continue
            seen.add(key)
            payload = {
                name: getattr(field.annotation, "__name__", repr(field.annotation))
                for name, field in event_model.model_fields.items()
            }
            events.append(
                {
                    "event": event_type,
                    "method": method,
                    "path": route.path,
                    "payload": payload,
                }
            )

    events.sort(key=lambda e: e["event"])
    return events


def render_payload(payload: dict[str, str]) -> str:
    """Render payload field names as Markdown links to the OpenAPI schema."""
    if not payload:
        return "\u2014"
    return ", ".join(
        f"[`{key}`]({API_DOCS_BASE}/{cls})" for key, cls in payload.items()
    )


def generate_markdown(events: list[dict]) -> str:
    """Render the full Markdown document."""
    lines = [HEADER]

    groups: dict[str, list[dict]] = {}
    for event in events:
        prefix = event["event"].split(".")[0]
        groups.setdefault(prefix, []).append(event)

    ordered_prefixes = list(GROUPS.keys()) + [p for p in groups if p not in GROUPS]

    for prefix in ordered_prefixes:
        if prefix not in groups:
            continue
        title = GROUPS.get(prefix, f"{prefix.replace('_', ' ').title()} Events")
        lines.append(f"### {title}\n")
        lines.append("| Event | HTTP Trigger | Payload |")
        lines.append("|-------|-------------|---------|")
        for event in groups[prefix]:
            payload_str = render_payload(event["payload"])
            lines.append(
                f"| `{event['event']}` "
                f"| `{event['method']} {event['path']}` "
                f"| {payload_str} |"
            )
        lines.append("")

    return "\n".join(lines)


app = typer.Typer(help="Generate webhook events reference page.")


@app.command()
def export_webhook_docs(
    output: Path = typer.Argument(
        default="webhook-events.md", help="Path where to export"
    ),
):
    from app.main import (
        app as f_app,  # imported here to avoid side-effects at module level
    )

    events = build_event_list(f_app)
    if not events:
        raise typer.Exit(1)
    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generate_markdown(events))


if __name__ == "__main__":
    app()
