#!/usr/bin/env python3
"""Generate docs/docs/developer-guide/webhook-events.md from router source files.

Usage:
    python scripts/generate_webhook_docs.py

Run this after modifying v2 event emissions in any router, then commit the output.
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
DOCS_OUTPUT = REPO_ROOT / "docs/docs/developer-guide/webhook-events.md"
API_DOCS_BASE = "/docs/api/#schema"

# Display names and order for event groups (keyed by event name prefix)
GROUPS = {
    "data_product": "Data Product Events",
    "output_port": "Output Port Events",
    "technical_asset": "Technical Asset Events",
}

HEADER = """\
---
title: Webhook Events (v2)
description: Reference for all v2 webhook events emitted by the Data Product Portal
sidebar_position: 9
---

<!-- Auto-generated by scripts/generate_webhook_docs.py — do not edit manually -->

The Data Product Portal emits webhook events following the [CloudEvents](https://cloudevents.io/) specification.
All events are delivered as HTTP POST requests to the configured endpoint.

## Configuration

Set the `WEBHOOK_V2_URL` environment variable to receive events.
When not set, no events are emitted.

## Envelope

Every event is wrapped in a CloudEvents envelope:

```json
{
  "specversion": "1.0",
  "id": "<uuid>",
  "source": "data-product-portal",
  "type": "data_product.created",
  "time": "2026-04-18T12:00:00Z",
  "data": { ... }
}
```

## Events

"""


def find_router_files() -> list[Path]:
    """Find all router.py files that emit v2 events."""
    return [
        p
        for p in (REPO_ROOT / "backend/app").rglob("router.py")
        if "from app.core.webhooks.v2 import" in p.read_text()
    ]


def extract_base_path(content: str) -> str:
    """Extract the base URL path from a router file.

    Two conventions:
    - Module-level: route = "/v2/..."
    - APIRouter constructor: router = APIRouter(prefix="/v2/...")
    """
    # Convention 1: route = "/v2/..." (possibly wrapped in parentheses across lines)
    m = re.search(r'^route\s*=\s*[\(\s]*"([^"]+)"', content, re.MULTILINE)
    if m:
        return m.group(1)
    # Convention 2: APIRouter(prefix="/v2/...")
    m = re.search(r'APIRouter\([^)]*prefix\s*=\s*"([^"]+)"', content)
    if m:
        return m.group(1)
    return ""


def extract_emit_definitions(content: str) -> dict[str, dict]:
    """Extract _emit_* variable definitions.

    Returns:
        {var_name: {"event": "event.name", "payload": {"key": "SchemaClass"}}}
    """
    pattern = re.compile(
        r'(_emit_\w+)\s*=\s*emit_event(?:_after)?\(\s*"([\w.]+)".*?\{(.*?)\}\s*,\s*\)',
        re.DOTALL,
    )
    result = {}
    for m in pattern.finditer(content):
        var_name = m.group(1)
        event_name = m.group(2)
        body = m.group(3)
        payload = {}
        for key_m in re.finditer(r'"(\w+)":\s*(\w+)\.model_validate', body):
            payload[key_m.group(1)] = key_m.group(2)
        result[var_name] = {"event": event_name, "payload": payload}
    return result


def resolve_path(path_expr: str, base_path: str) -> str:
    """Resolve a path expression from a route decorator to a full URL path.

    Handles:
    - route             → base_path
    - f"{route}/suffix" → base_path + /suffix  ({{x}} → {x})
    - "/suffix"         → base_path + /suffix  (relative literal)
    - ""                → base_path
    """
    if path_expr == "route":
        return base_path
    if path_expr.startswith('f"'):
        inner = path_expr[2:-1]  # strip f" and "
        inner = inner.replace("{route}", base_path)
        inner = inner.replace("{{", "{").replace("}}", "}")
        return inner
    # Quoted string — relative to base_path
    value = path_expr.strip('"')
    return base_path + value


def extract_routes(content: str, base_path: str) -> list[dict]:
    """Extract route definitions that have emit dependencies.

    Returns:
        [{"method": "POST", "path": "/v2/...", "emit_vars": ["_emit_xxx"]}]
    """
    dec_pattern = re.compile(
        r"@(?:_router|router)\.(post|put|delete|get|patch)\s*\(\s*"
        r'(route|f"[^"]*"|"[^"]*")',
    )
    routes = []
    for dec_m in dec_pattern.finditer(content):
        method = dec_m.group(1).upper()
        path_expr = dec_m.group(2)
        path = resolve_path(path_expr, base_path)

        # Find the block from this decorator up to the next function definition
        block_start = dec_m.start()
        next_def = re.search(r"\ndef\s+|\nasync def\s+", content[block_start:])
        block_end = block_start + (next_def.start() if next_def else 2000)
        block = content[block_start:block_end]

        emit_vars = re.findall(r"Depends\((_emit_\w+)\)", block)
        if emit_vars:
            routes.append({"method": method, "path": path, "emit_vars": emit_vars})

    return routes


def build_event_list(router_files: list[Path]) -> list[dict]:
    """Build the full list of events from all router files."""
    all_events = []
    seen = set()

    for router_file in sorted(router_files):
        content = router_file.read_text()
        base_path = extract_base_path(content)
        emit_defs = extract_emit_definitions(content)
        routes = extract_routes(content, base_path)

        for route in routes:
            for emit_var in route["emit_vars"]:
                if emit_var not in emit_defs:
                    continue
                key = (emit_defs[emit_var]["event"], route["method"], route["path"])
                if key in seen:
                    continue
                seen.add(key)
                all_events.append(
                    {
                        **emit_defs[emit_var],
                        "method": route["method"],
                        "path": route["path"],
                    }
                )

    all_events.sort(key=lambda e: e["event"])
    return all_events


def render_payload(payload: dict[str, str]) -> str:
    """Render payload keys as Markdown links to OpenAPI schema."""
    if not payload:
        return "—"
    return ", ".join(
        f"[`{key}`]({API_DOCS_BASE}/{cls})" for key, cls in payload.items()
    )


def generate_markdown(events: list[dict]) -> str:
    """Render events as Markdown documentation."""
    lines = [HEADER]

    # Group events by subject prefix
    groups: dict[str, list[dict]] = {}
    for event in events:
        prefix = event["event"].split(".")[0]
        groups.setdefault(prefix, []).append(event)

    # Emit sections in defined order first, then any extras
    ordered_prefixes = list(GROUPS.keys()) + [p for p in groups if p not in GROUPS]

    for prefix in ordered_prefixes:
        if prefix not in groups:
            continue
        title = GROUPS.get(prefix, f"{prefix.replace('_', ' ').title()} Events")
        lines.append(f"### {title}\n")
        lines.append("| Event | HTTP Trigger | Payload |")
        lines.append("|-------|-------------|---------|")
        for event in groups[prefix]:
            payload_str = render_payload(event["payload"])
            lines.append(
                f"| `{event['event']}` "
                f"| `{event['method']} {event['path']}` "
                f"| {payload_str} |"
            )
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    router_files = find_router_files()
    if not router_files:
        print("No router files with v2 events found!", file=sys.stderr)
        sys.exit(1)

    events = build_event_list(router_files)
    if not events:
        print("No events extracted from router files!", file=sys.stderr)
        sys.exit(1)

    markdown = generate_markdown(events)
    DOCS_OUTPUT.write_text(markdown)
    print(f"Generated {DOCS_OUTPUT.relative_to(REPO_ROOT)} with {len(events)} events.")


if __name__ == "__main__":
    main()
