development:
  aws:
    account_id: "012345678901"
    region: eu-west-1
    can_read_from:
    - production
    s3:
      - identifier: datalake
        bucket_arn: arn:aws:s3:::default-dev
        bucket_name: default-dev
        is_default: true
        kms_key_arn: arn:aws:kms:kms-key-arn
      - identifier: other_bucket
        bucket_arn: arn:aws:s3:::non-default-dev
        bucket_name: non-default-dev
        is_default: false
        kms_key_arn: arn:aws:kms:kms-key-arn
production:
  aws:
    account_id: "012345678901"
    region: eu-west-1
    can_read_from: []
    s3:
      - identifier: datalake
        bucket_arn: arn:aws:s3:::default-prd
        bucket_name: default-prd
        is_default: true
        kms_key_arn: arn:aws:kms:kms-key-arn
      - identifier: other_bucket
        bucket_arn: arn:aws:s3:::non-default-prd
        bucket_name: non-default-prd
        is_default: false
        kms_key_arn: arn:aws:kms:kms-key-arn
