sales_crm_customer:
  outputs:
    dev:
      dbname: dpp_demo
      host: localhost
      pass: abc123
      port: 5433
      schema: sales_crm_customer
      threads: 1
      type: postgres
      user: postgres
  target: dev
