version: '3'

tasks:
  poetry:sync:
    desc: Sync poetry requirements
    cmds:
      - cp ../backend/requirements-poetry.txt basic/provisioner/requirements-poetry.txt
      - cp ../backend/requirements-poetry.txt agents/provisioner/requirements-poetry.txt

  poetry:update:
    desc: Update dependencies
    cmds:
      - cd basic/products && poetry update
      - cd basic/provisioner && poetry update
      - cd agents/agent && uv pip compile requirements-poetry.in --python-platform linux --python-version 3.13  -o requirements-poetry.txt --generate-hashes && poetry update
      - cd agents/provisioner && poetry update
