export const EventType = {
    DATA_OUTPUT_CREATED: 'data_output_created',
    DATA_OUTPUT_REMOVED: 'data_output_removed',
    DATA_OUTPUT_STATUS_UPDATED: 'data_output_status_updated',
    DATA_OUTPUT_LINK_REQUESTED_TO_DATASET: 'data_output_link_requested_to_dataset',
    DATA_OUTPUT_LINK_REMOVED_FROM_DATASET: 'data_output_link_removed_from_dataset',
    DATA_OUTPUT_UPDATED: 'data_output_updated',
    DATA_OUTPUT_LINK_TO_DATASET_APPROVED: 'data_output_link_to_dataset_approved',
    DATA_OUTPUT_LINK_TO_DATASET_DENIED: 'data_output_link_to_dataset_denied',
    DATA_OUTPUT_LINK_TO_DATASET_REMOVED: 'data_output_link_to_dataset_removed',
    DATA_PRODUCT_MEMBERSHIP_REQUESTED: 'data_product_membership_requested',
    DATA_PRODUCT_MEMBERSHIP_APPROVED: 'data_product_membership_approved',
    DATA_PRODUCT_MEMBERSHIP_DENIED: 'data_product_membership_denied',
    DATA_PRODUCT_MEMBERSHIP_REMOVED: 'data_product_membership_removed',
    DATA_PRODUCT_MEMBERSHIP_CREATED: 'data_product_membership_created',
    DATA_PRODUCT_MEMBERSHIP_UPDATED: 'data_product_membership_updated',
    DATA_PRODUCT_CREATION_MEMBERSHIP_ADDED: 'data_product_creation_membership_added',
    DATA_PRODUCT_CREATED: 'data_product_created',
    DATA_PRODUCT_DELETED: 'data_product_deleted',
    DATA_PRODUCT_UPDATE_MEMBERSHIP_UPDATED: 'data_product_update_membership_updated',
    DATA_PRODUCT_UPDATE_MEMBERSHIP_REMOVED: 'data_product_update_membership_removed',
    DATA_PRODUCT_UPDATE_MEMBERSHIP_ADDED: 'data_product_update_membership_added',
    DATA_PRODUCT_UPDATED: 'data_product_updated',
    DATA_PRODUCT_ABOUT_UPDATED: 'data_product_about_updated',
    DATA_PRODUCT_STATUS_UPDATED: 'data_product_status_updated',
    DATA_PRODUCT_REQUESTED_ACCESS_TO_DATASET: 'data_product_requested_access_to_dataset',
    DATA_PRODUCT_LINKED_TO_DATASET: 'data_product_linked_to_dataset',
    DATA_PRODUCT_ACCESS_REQUEST_TO_DATASET_REMOVED: 'data_product_access_request_to_dataset_removed',
    DATA_PRODUCT_UNLINKED_FROM_DATASET: 'data_product_unlinked_from_dataset',
    DATA_PRODUCT_LINK_TO_DATASET_APPROVED: 'data_product_link_to_dataset_approved',
    DATA_PRODUCT_LINK_TO_DATASET_DENIED: 'data_product_link_to_dataset_denied',
    DATA_PRODUCT_LINK_TO_DATASET_REMOVED: 'data_product_link_to_dataset_removed',
    DATASET_CREATION_OWNER_ADDED: 'dataset_creation_owner_added',
    DATASET_CREATED: 'dataset_created',
    DATASET_REMOVED: 'dataset_removed',
    DATASET_UPDATE_OWNER_REMOVED: 'dataset_update_owner_removed',
    DATASET_UPDATE_OWNER_ADDED: 'dataset_update_owner_added',
    DATASET_UPDATED: 'dataset_updated',
    DATASET_ABOUT_UPDATED: 'dataset_about_updated',
    DATASET_STATUS_UPDATED: 'dataset_status_updated',
    USER_ADDED_TO_DATASET: 'user_added_to_dataset',
    USER_REMOVED_FROM_DATASET: 'user_removed_from_dataset',
} as const;

export type EventType = (typeof EventType)[keyof typeof EventType];
