// Code generated by oapi-codegen. DO NOT EDIT.

package portalsdk

import (
	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/google/uuid"
)

type CheckAccessPath struct {
	Action AuthorizationAction `json:"action" validate:"required"`
}

func (c CheckAccessPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(c.Action).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Action", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetOutputPortQueryStatsPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	ID            uuid.UUID `json:"id" validate:"required"`
}

func (g GetOutputPortQueryStatsPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type UpdateOutputPortQueryStatsPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	ID            uuid.UUID `json:"id" validate:"required"`
}

func (u UpdateOutputPortQueryStatsPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(u.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(u.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type DeleteOutputPortQueryStatPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	ID            uuid.UUID `json:"id" validate:"required"`
}

func (d DeleteOutputPortQueryStatPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(d.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(d.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetOutputPortCuratedQueriesPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	ID            uuid.UUID `json:"id" validate:"required"`
}

func (g GetOutputPortCuratedQueriesPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type ReplaceOutputPortCuratedQueriesPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	ID            uuid.UUID `json:"id" validate:"required"`
}

func (r ReplaceOutputPortCuratedQueriesPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(r.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(r.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetDataProductOutputPortsPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
}

func (g GetDataProductOutputPortsPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type CreateOutputPortPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
}

func (c CreateOutputPortPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(c.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetOutputPortPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	ID            uuid.UUID `json:"id" validate:"required"`
}

func (g GetOutputPortPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type RemoveDatasetPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	ID            uuid.UUID `json:"id" validate:"required"`
}

func (r RemoveDatasetPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(r.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(r.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type UpdateOutputPortPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	ID            uuid.UUID `json:"id" validate:"required"`
}

func (u UpdateOutputPortPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(u.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(u.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetOutputPortsEventHistoryPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	ID            uuid.UUID `json:"id" validate:"required"`
}

func (g GetOutputPortsEventHistoryPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type UpdateOutputPortAboutPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	ID            uuid.UUID `json:"id" validate:"required"`
}

func (u UpdateOutputPortAboutPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(u.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(u.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type UpdateOutputPortStatusPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	ID            uuid.UUID `json:"id" validate:"required"`
}

func (u UpdateOutputPortStatusPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(u.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(u.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetOutputPortGraphDataPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	ID            uuid.UUID `json:"id" validate:"required"`
}

func (g GetOutputPortGraphDataPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type SetValueForOutputPortPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	ID            uuid.UUID `json:"id" validate:"required"`
	SettingID     uuid.UUID `json:"setting_id" validate:"required"`
}

func (s SetValueForOutputPortPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(s.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(s.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if v, ok := any(s.SettingID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("SettingID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type RemoveDataProductPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (r RemoveDataProductPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(r.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type UpdateDataProductPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (u UpdateDataProductPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(u.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetDataProductPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (g GetDataProductPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type UpdateDataProductAboutPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (u UpdateDataProductAboutPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(u.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type UpdateDataProductStatusPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (u UpdateDataProductStatusPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(u.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type UpdateDataProductUsagePath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (u UpdateDataProductUsagePath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(u.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetDataProductGraphDataPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (g GetDataProductGraphDataPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type SetValueForDataProductPath struct {
	ID        uuid.UUID `json:"id" validate:"required"`
	SettingID uuid.UUID `json:"setting_id" validate:"required"`
}

func (s SetValueForDataProductPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(s.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if v, ok := any(s.SettingID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("SettingID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type LinkInputPortsToDataProductPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (l LinkInputPortsToDataProductPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(l.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetDataProductEventHistoryPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (g GetDataProductEventHistoryPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type CreateTechnicalAssetPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (c CreateTechnicalAssetPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(c.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetSigninURLPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (g GetSigninURLPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetConveyorIdeURLPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (g GetConveyorIdeURLPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetDatabricksWorkspaceURLPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (g GetDatabricksWorkspaceURLPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetSnowflakeURLPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (g GetSnowflakeURLPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetTechnicalAssetsPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (g GetTechnicalAssetsPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetDataProductInputPortsPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (g GetDataProductInputPortsPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetDataProductRolledUpTagsPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (g GetDataProductRolledUpTagsPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type UnlinkInputPortFromDataProductPath struct {
	ID          uuid.UUID `json:"id" validate:"required"`
	InputPortID uuid.UUID `json:"input_port_id" validate:"required"`
}

func (u UnlinkInputPortFromDataProductPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(u.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if v, ok := any(u.InputPortID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("InputPortID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetDataProductTypePath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (g GetDataProductTypePath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type UpdateDataProductTypePath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (u UpdateDataProductTypePath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(u.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type RemoveDataProductTypePath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (r RemoveDataProductTypePath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(r.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type MigrateDataProductTypePath struct {
	FromID uuid.UUID `json:"from_id" validate:"required"`
	ToID   uuid.UUID `json:"to_id" validate:"required"`
}

func (m MigrateDataProductTypePath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(m.FromID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("FromID", err)
		}
	}
	if v, ok := any(m.ToID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ToID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type UpdateDataProductLifecyclePath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (u UpdateDataProductLifecyclePath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(u.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type RemoveDataProductLifecyclePath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (r RemoveDataProductLifecyclePath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(r.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type UpdateDataProductSettingPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (u UpdateDataProductSettingPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(u.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type RemoveDataProductSettingPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (r RemoveDataProductSettingPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(r.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type ApproveOutputPortAsInputPortPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	OutputPortID  uuid.UUID `json:"output_port_id" validate:"required"`
}

func (a ApproveOutputPortAsInputPortPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(a.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(a.OutputPortID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("OutputPortID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type DenyOutputPortAsInputPortPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	OutputPortID  uuid.UUID `json:"output_port_id" validate:"required"`
}

func (d DenyOutputPortAsInputPortPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(d.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(d.OutputPortID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("OutputPortID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type RemoveOutputPortAsInputPortPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	OutputPortID  uuid.UUID `json:"output_port_id" validate:"required"`
}

func (r RemoveOutputPortAsInputPortPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(r.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(r.OutputPortID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("OutputPortID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type ApproveOutputPortTechnicalAssetLinkPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	OutputPortID  uuid.UUID `json:"output_port_id" validate:"required"`
}

func (a ApproveOutputPortTechnicalAssetLinkPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(a.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(a.OutputPortID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("OutputPortID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type DenyOutputPortTechnicalAssetLinkPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	OutputPortID  uuid.UUID `json:"output_port_id" validate:"required"`
}

func (d DenyOutputPortTechnicalAssetLinkPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(d.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(d.OutputPortID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("OutputPortID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type LinkOutputPortToTechnicalAssetPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	OutputPortID  uuid.UUID `json:"output_port_id" validate:"required"`
}

func (l LinkOutputPortToTechnicalAssetPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(l.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(l.OutputPortID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("OutputPortID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type UnlinkOutputPortFromTechnicalAssetPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	OutputPortID  uuid.UUID `json:"output_port_id" validate:"required"`
}

func (u UnlinkOutputPortFromTechnicalAssetPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(u.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(u.OutputPortID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("OutputPortID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetTechnicalAssetPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	ID            uuid.UUID `json:"id" validate:"required"`
}

func (g GetTechnicalAssetPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type RemoveTechnicalAssetPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	ID            uuid.UUID `json:"id" validate:"required"`
}

func (r RemoveTechnicalAssetPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(r.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(r.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetTechnicalAssetEventHistoryPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	ID            uuid.UUID `json:"id" validate:"required"`
}

func (g GetTechnicalAssetEventHistoryPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type UpdateTechnicalAssetStatusPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	ID            uuid.UUID `json:"id" validate:"required"`
}

func (u UpdateTechnicalAssetStatusPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(u.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(u.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetTechnicalAssetGraphDataPath struct {
	DataProductID uuid.UUID `json:"data_product_id" validate:"required"`
	ID            uuid.UUID `json:"id" validate:"required"`
}

func (g GetTechnicalAssetGraphDataPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.DataProductID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("DataProductID", err)
		}
	}
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type UpdateDomainPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (u UpdateDomainPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(u.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type RemoveDomainPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (r RemoveDomainPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(r.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetDomainPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (g GetDomainPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type MigrateDomainPath struct {
	FromID uuid.UUID `json:"from_id" validate:"required"`
	ToID   uuid.UUID `json:"to_id" validate:"required"`
}

func (m MigrateDomainPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(m.FromID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("FromID", err)
		}
	}
	if v, ok := any(m.ToID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ToID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetEnvironmentPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (g GetEnvironmentPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetEnvironmentConfigsByIDPath struct {
	ConfigID uuid.UUID `json:"config_id" validate:"required"`
}

func (g GetEnvironmentConfigsByIDPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.ConfigID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ConfigID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetEnvironmentPlatformServiceConfigPath struct {
	ID         uuid.UUID `json:"id" validate:"required"`
	PlatformID uuid.UUID `json:"platform_id" validate:"required"`
	ServiceID  uuid.UUID `json:"service_id" validate:"required"`
}

func (g GetEnvironmentPlatformServiceConfigPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if v, ok := any(g.PlatformID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("PlatformID", err)
		}
	}
	if v, ok := any(g.ServiceID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ServiceID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetEnvironmentPlatformConfigPath struct {
	ID         uuid.UUID `json:"id" validate:"required"`
	PlatformID uuid.UUID `json:"platform_id" validate:"required"`
}

func (g GetEnvironmentPlatformConfigPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if v, ok := any(g.PlatformID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("PlatformID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetEnvironmentConfigsPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (g GetEnvironmentConfigsPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetEnvironmentPlatformServiceConfigForAllEnvsPath struct {
	PlatformID uuid.UUID `json:"platform_id" validate:"required"`
	ServiceID  uuid.UUID `json:"service_id" validate:"required"`
}

func (g GetEnvironmentPlatformServiceConfigForAllEnvsPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.PlatformID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("PlatformID", err)
		}
	}
	if v, ok := any(g.ServiceID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ServiceID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetPlatformServiceConfigPath struct {
	ID        uuid.UUID `json:"id" validate:"required"`
	ServiceID uuid.UUID `json:"service_id" validate:"required"`
}

func (g GetPlatformServiceConfigPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if v, ok := any(g.ServiceID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ServiceID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetSinglePlatformServiceConfigurationPath struct {
	ConfigID uuid.UUID `json:"config_id" validate:"required"`
}

func (g GetSinglePlatformServiceConfigurationPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.ConfigID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ConfigID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetPlatformServicesPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (g GetPlatformServicesPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type UpdateTagPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (u UpdateTagPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(u.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type RemoveTagPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (r RemoveTagPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(r.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type RemoveUserPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (r RemoveUserPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(r.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type RemoveRolePath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (r RemoveRolePath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(r.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type UpdateRolePath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (u UpdateRolePath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(u.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetRolesPath struct {
	Scope Scope `json:"scope" validate:"required"`
}

func (g GetRolesPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(g.Scope).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Scope", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type DeleteGlobalRoleAssignmentPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (d DeleteGlobalRoleAssignmentPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(d.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type DecideGlobalRoleAssignmentPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (d DecideGlobalRoleAssignmentPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(d.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type ModifyGlobalRoleAssignmentPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (m ModifyGlobalRoleAssignmentPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(m.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type DeleteDataProductRoleAssignmentPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (d DeleteDataProductRoleAssignmentPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(d.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type ModifyDataProductRoleAssignmentPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (m ModifyDataProductRoleAssignmentPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(m.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type DecideDataProductRoleAssignmentPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (d DecideDataProductRoleAssignmentPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(d.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type DeleteOutputPortRoleAssignmentPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (d DeleteOutputPortRoleAssignmentPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(d.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type ModifyOutputPortRoleAssignmentPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (m ModifyOutputPortRoleAssignmentPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(m.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type DecideOutputPortRoleAssignmentPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (d DecideOutputPortRoleAssignmentPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(d.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type RemoveUserNotificationPath struct {
	ID uuid.UUID `json:"id" validate:"required"`
}

func (r RemoveUserNotificationPath) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(r.ID).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("ID", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type GetPluginFormPath struct {
	PluginName string `json:"plugin_name" validate:"required"`
}

func (g GetPluginFormPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}
