sales_erp_orders:
  outputs:
    dev:
      dbname: dpp_demo
      host: localhost
      pass: abc123
      port: 5433
      schema: sales_erp_orders
      threads: 1
      type: postgres
      user: postgres
  target: dev
