// Code generated by oapi-codegen. DO NOT EDIT.

package portalsdk

import (
	"encoding/json"
	"errors"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/google/uuid"
)

type CreateGlobalRoleAssignment_RoleID_AnyOf_0 = uuid.UUID

type Edge_ID_AnyOf_1 = uuid.UUID

type Edge_Source_AnyOf_1 = uuid.UUID

type Edge_Target_AnyOf_1 = uuid.UUID

type ModifyGlobalRoleAssignment_RoleID_AnyOf_0 = uuid.UUID

type Node_ID_AnyOf_1 = uuid.UUID

type NodeData_ID_AnyOf_1 = uuid.UUID

type NodeData_LinkToID_AnyOf_1 = uuid.UUID

type NodeData_DomainID_AnyOf_1 = uuid.UUID

type CreateGlobalRoleAssignment_RoleID_AnyOf struct {
	runtime.Either[CreateGlobalRoleAssignment_RoleID_AnyOf_0, string]
}

func (c *CreateGlobalRoleAssignment_RoleID_AnyOf) Validate() error {
	if c.IsA() {
		if v, ok := any(c.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if c.IsB() {
		if v, ok := any(c.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

type CreateTechnicalAssetRequest_Configuration_OneOf struct {
	union json.RawMessage
}

func (c *CreateTechnicalAssetRequest_Configuration_OneOf) Validate() error {
	// NOTE: Validation is not supported for unions with more than 2 elements.
	// Validating would require unmarshaling against each possible type, which is inefficient.
	// Use AsValidated<Type>() methods to validate after retrieving the specific type.
	return nil
}

// Raw returns the union data inside the CreateTechnicalAssetRequest_Configuration_OneOf as bytes
func (c *CreateTechnicalAssetRequest_Configuration_OneOf) Raw() json.RawMessage {
	return c.union
}

// AsS3DataOutput returns the union data inside the CreateTechnicalAssetRequest_Configuration_OneOf as a S3DataOutput
func (c *CreateTechnicalAssetRequest_Configuration_OneOf) AsS3DataOutput() (S3DataOutput, error) {
	return runtime.UnmarshalAs[S3DataOutput](c.union)
}

// AsValidatedS3DataOutput returns the union data inside the CreateTechnicalAssetRequest_Configuration_OneOf as a validated S3DataOutput
func (c *CreateTechnicalAssetRequest_Configuration_OneOf) AsValidatedS3DataOutput() (S3DataOutput, error) {
	val, err := c.AsS3DataOutput()
	if err != nil {
		var zero S3DataOutput
		return zero, err
	}
	if err := c.validateS3DataOutput(val); err != nil {
		var zero S3DataOutput
		return zero, err
	}
	return val, nil
}

// FromS3DataOutput overwrites any union data inside the CreateTechnicalAssetRequest_Configuration_OneOf as the provided S3DataOutput
func (c *CreateTechnicalAssetRequest_Configuration_OneOf) FromS3DataOutput(val S3DataOutput) error {
	// Validate before storing
	if err := c.validateS3DataOutput(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	c.union = bts
	return err
}

// AsGlueDataOutput returns the union data inside the CreateTechnicalAssetRequest_Configuration_OneOf as a GlueDataOutput
func (c *CreateTechnicalAssetRequest_Configuration_OneOf) AsGlueDataOutput() (GlueDataOutput, error) {
	return runtime.UnmarshalAs[GlueDataOutput](c.union)
}

// AsValidatedGlueDataOutput returns the union data inside the CreateTechnicalAssetRequest_Configuration_OneOf as a validated GlueDataOutput
func (c *CreateTechnicalAssetRequest_Configuration_OneOf) AsValidatedGlueDataOutput() (GlueDataOutput, error) {
	val, err := c.AsGlueDataOutput()
	if err != nil {
		var zero GlueDataOutput
		return zero, err
	}
	if err := c.validateGlueDataOutput(val); err != nil {
		var zero GlueDataOutput
		return zero, err
	}
	return val, nil
}

// FromGlueDataOutput overwrites any union data inside the CreateTechnicalAssetRequest_Configuration_OneOf as the provided GlueDataOutput
func (c *CreateTechnicalAssetRequest_Configuration_OneOf) FromGlueDataOutput(val GlueDataOutput) error {
	// Validate before storing
	if err := c.validateGlueDataOutput(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	c.union = bts
	return err
}

// AsDatabricksDataOutput returns the union data inside the CreateTechnicalAssetRequest_Configuration_OneOf as a DatabricksDataOutput
func (c *CreateTechnicalAssetRequest_Configuration_OneOf) AsDatabricksDataOutput() (DatabricksDataOutput, error) {
	return runtime.UnmarshalAs[DatabricksDataOutput](c.union)
}

// AsValidatedDatabricksDataOutput returns the union data inside the CreateTechnicalAssetRequest_Configuration_OneOf as a validated DatabricksDataOutput
func (c *CreateTechnicalAssetRequest_Configuration_OneOf) AsValidatedDatabricksDataOutput() (DatabricksDataOutput, error) {
	val, err := c.AsDatabricksDataOutput()
	if err != nil {
		var zero DatabricksDataOutput
		return zero, err
	}
	if err := c.validateDatabricksDataOutput(val); err != nil {
		var zero DatabricksDataOutput
		return zero, err
	}
	return val, nil
}

// FromDatabricksDataOutput overwrites any union data inside the CreateTechnicalAssetRequest_Configuration_OneOf as the provided DatabricksDataOutput
func (c *CreateTechnicalAssetRequest_Configuration_OneOf) FromDatabricksDataOutput(val DatabricksDataOutput) error {
	// Validate before storing
	if err := c.validateDatabricksDataOutput(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	c.union = bts
	return err
}

// AsSnowflakeDataOutput returns the union data inside the CreateTechnicalAssetRequest_Configuration_OneOf as a SnowflakeDataOutput
func (c *CreateTechnicalAssetRequest_Configuration_OneOf) AsSnowflakeDataOutput() (SnowflakeDataOutput, error) {
	return runtime.UnmarshalAs[SnowflakeDataOutput](c.union)
}

// AsValidatedSnowflakeDataOutput returns the union data inside the CreateTechnicalAssetRequest_Configuration_OneOf as a validated SnowflakeDataOutput
func (c *CreateTechnicalAssetRequest_Configuration_OneOf) AsValidatedSnowflakeDataOutput() (SnowflakeDataOutput, error) {
	val, err := c.AsSnowflakeDataOutput()
	if err != nil {
		var zero SnowflakeDataOutput
		return zero, err
	}
	if err := c.validateSnowflakeDataOutput(val); err != nil {
		var zero SnowflakeDataOutput
		return zero, err
	}
	return val, nil
}

// FromSnowflakeDataOutput overwrites any union data inside the CreateTechnicalAssetRequest_Configuration_OneOf as the provided SnowflakeDataOutput
func (c *CreateTechnicalAssetRequest_Configuration_OneOf) FromSnowflakeDataOutput(val SnowflakeDataOutput) error {
	// Validate before storing
	if err := c.validateSnowflakeDataOutput(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	c.union = bts
	return err
}

// AsRedshiftDataOutput returns the union data inside the CreateTechnicalAssetRequest_Configuration_OneOf as a RedshiftDataOutput
func (c *CreateTechnicalAssetRequest_Configuration_OneOf) AsRedshiftDataOutput() (RedshiftDataOutput, error) {
	return runtime.UnmarshalAs[RedshiftDataOutput](c.union)
}

// AsValidatedRedshiftDataOutput returns the union data inside the CreateTechnicalAssetRequest_Configuration_OneOf as a validated RedshiftDataOutput
func (c *CreateTechnicalAssetRequest_Configuration_OneOf) AsValidatedRedshiftDataOutput() (RedshiftDataOutput, error) {
	val, err := c.AsRedshiftDataOutput()
	if err != nil {
		var zero RedshiftDataOutput
		return zero, err
	}
	if err := c.validateRedshiftDataOutput(val); err != nil {
		var zero RedshiftDataOutput
		return zero, err
	}
	return val, nil
}

// FromRedshiftDataOutput overwrites any union data inside the CreateTechnicalAssetRequest_Configuration_OneOf as the provided RedshiftDataOutput
func (c *CreateTechnicalAssetRequest_Configuration_OneOf) FromRedshiftDataOutput(val RedshiftDataOutput) error {
	// Validate before storing
	if err := c.validateRedshiftDataOutput(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	c.union = bts
	return err
}

// validateS3DataOutput validates a S3DataOutput value
func (c *CreateTechnicalAssetRequest_Configuration_OneOf) validateS3DataOutput(val S3DataOutput) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateGlueDataOutput validates a GlueDataOutput value
func (c *CreateTechnicalAssetRequest_Configuration_OneOf) validateGlueDataOutput(val GlueDataOutput) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateDatabricksDataOutput validates a DatabricksDataOutput value
func (c *CreateTechnicalAssetRequest_Configuration_OneOf) validateDatabricksDataOutput(val DatabricksDataOutput) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateSnowflakeDataOutput validates a SnowflakeDataOutput value
func (c *CreateTechnicalAssetRequest_Configuration_OneOf) validateSnowflakeDataOutput(val SnowflakeDataOutput) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateRedshiftDataOutput validates a RedshiftDataOutput value
func (c *CreateTechnicalAssetRequest_Configuration_OneOf) validateRedshiftDataOutput(val RedshiftDataOutput) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

func (c CreateTechnicalAssetRequest_Configuration_OneOf) discriminator(data []byte) (string, error) {
	var discriminator struct {
		Value string `json:"configuration_type"`
	}
	if err := json.Unmarshal(data, &discriminator); err != nil {
		return "", err
	}
	return discriminator.Value, nil
}

func (c CreateTechnicalAssetRequest_Configuration_OneOf) ValueByDiscriminator() (any, error) {
	discriminator, err := c.discriminator(c.union)
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "DatabricksDataOutput":
		return c.AsDatabricksDataOutput()
	case "GlueDataOutput":
		return c.AsGlueDataOutput()
	case "RedshiftDataOutput":
		return c.AsRedshiftDataOutput()
	case "S3DataOutput":
		return c.AsS3DataOutput()
	case "SnowflakeDataOutput":
		return c.AsSnowflakeDataOutput()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (c CreateTechnicalAssetRequest_Configuration_OneOf) MarshalJSON() ([]byte, error) {
	bts, err := c.union.MarshalJSON()

	return bts, err
}

func (c *CreateTechnicalAssetRequest_Configuration_OneOf) UnmarshalJSON(bts []byte) error {
	err := c.union.UnmarshalJSON(bts)

	return err
}

type Edge_ID_AnyOf struct {
	runtime.Either[string, Edge_ID_AnyOf_1]
}

func (e *Edge_ID_AnyOf) Validate() error {
	if e.IsA() {
		if v, ok := any(e.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if e.IsB() {
		if v, ok := any(e.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

type Edge_Source_AnyOf struct {
	runtime.Either[string, Edge_Source_AnyOf_1]
}

func (e *Edge_Source_AnyOf) Validate() error {
	if e.IsA() {
		if v, ok := any(e.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if e.IsB() {
		if v, ok := any(e.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

type Edge_Target_AnyOf struct {
	runtime.Either[string, Edge_Target_AnyOf_1]
}

func (e *Edge_Target_AnyOf) Validate() error {
	if e.IsA() {
		if v, ok := any(e.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if e.IsB() {
		if v, ok := any(e.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

type EnvironmentConfigsGetItem_Config_AnyOf struct {
	union json.RawMessage
}

func (e *EnvironmentConfigsGetItem_Config_AnyOf) Validate() error {
	// NOTE: Validation is not supported for unions with more than 2 elements.
	// Validating would require unmarshaling against each possible type, which is inefficient.
	// Use AsValidated<Type>() methods to validate after retrieving the specific type.
	return nil
}

// Raw returns the union data inside the EnvironmentConfigsGetItem_Config_AnyOf as bytes
func (e *EnvironmentConfigsGetItem_Config_AnyOf) Raw() json.RawMessage {
	return e.union
}

// AsAWSS3Config returns the union data inside the EnvironmentConfigsGetItem_Config_AnyOf as a AWSS3Config
func (e *EnvironmentConfigsGetItem_Config_AnyOf) AsAWSS3Config() (AWSS3Config, error) {
	return runtime.UnmarshalAs[AWSS3Config](e.union)
}

// AsValidatedAWSS3Config returns the union data inside the EnvironmentConfigsGetItem_Config_AnyOf as a validated AWSS3Config
func (e *EnvironmentConfigsGetItem_Config_AnyOf) AsValidatedAWSS3Config() (AWSS3Config, error) {
	val, err := e.AsAWSS3Config()
	if err != nil {
		var zero AWSS3Config
		return zero, err
	}
	if err := e.validateAWSS3Config(val); err != nil {
		var zero AWSS3Config
		return zero, err
	}
	return val, nil
}

// FromAWSS3Config overwrites any union data inside the EnvironmentConfigsGetItem_Config_AnyOf as the provided AWSS3Config
func (e *EnvironmentConfigsGetItem_Config_AnyOf) FromAWSS3Config(val AWSS3Config) error {
	// Validate before storing
	if err := e.validateAWSS3Config(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	e.union = bts
	return err
}

// AsAWSGlueConfig returns the union data inside the EnvironmentConfigsGetItem_Config_AnyOf as a AWSGlueConfig
func (e *EnvironmentConfigsGetItem_Config_AnyOf) AsAWSGlueConfig() (AWSGlueConfig, error) {
	return runtime.UnmarshalAs[AWSGlueConfig](e.union)
}

// AsValidatedAWSGlueConfig returns the union data inside the EnvironmentConfigsGetItem_Config_AnyOf as a validated AWSGlueConfig
func (e *EnvironmentConfigsGetItem_Config_AnyOf) AsValidatedAWSGlueConfig() (AWSGlueConfig, error) {
	val, err := e.AsAWSGlueConfig()
	if err != nil {
		var zero AWSGlueConfig
		return zero, err
	}
	if err := e.validateAWSGlueConfig(val); err != nil {
		var zero AWSGlueConfig
		return zero, err
	}
	return val, nil
}

// FromAWSGlueConfig overwrites any union data inside the EnvironmentConfigsGetItem_Config_AnyOf as the provided AWSGlueConfig
func (e *EnvironmentConfigsGetItem_Config_AnyOf) FromAWSGlueConfig(val AWSGlueConfig) error {
	// Validate before storing
	if err := e.validateAWSGlueConfig(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	e.union = bts
	return err
}

// AsDatabricksConfig returns the union data inside the EnvironmentConfigsGetItem_Config_AnyOf as a DatabricksConfig
func (e *EnvironmentConfigsGetItem_Config_AnyOf) AsDatabricksConfig() (DatabricksConfig, error) {
	return runtime.UnmarshalAs[DatabricksConfig](e.union)
}

// AsValidatedDatabricksConfig returns the union data inside the EnvironmentConfigsGetItem_Config_AnyOf as a validated DatabricksConfig
func (e *EnvironmentConfigsGetItem_Config_AnyOf) AsValidatedDatabricksConfig() (DatabricksConfig, error) {
	val, err := e.AsDatabricksConfig()
	if err != nil {
		var zero DatabricksConfig
		return zero, err
	}
	if err := e.validateDatabricksConfig(val); err != nil {
		var zero DatabricksConfig
		return zero, err
	}
	return val, nil
}

// FromDatabricksConfig overwrites any union data inside the EnvironmentConfigsGetItem_Config_AnyOf as the provided DatabricksConfig
func (e *EnvironmentConfigsGetItem_Config_AnyOf) FromDatabricksConfig(val DatabricksConfig) error {
	// Validate before storing
	if err := e.validateDatabricksConfig(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	e.union = bts
	return err
}

// AsSnowflakeConfig returns the union data inside the EnvironmentConfigsGetItem_Config_AnyOf as a SnowflakeConfig
func (e *EnvironmentConfigsGetItem_Config_AnyOf) AsSnowflakeConfig() (SnowflakeConfig, error) {
	return runtime.UnmarshalAs[SnowflakeConfig](e.union)
}

// AsValidatedSnowflakeConfig returns the union data inside the EnvironmentConfigsGetItem_Config_AnyOf as a validated SnowflakeConfig
func (e *EnvironmentConfigsGetItem_Config_AnyOf) AsValidatedSnowflakeConfig() (SnowflakeConfig, error) {
	val, err := e.AsSnowflakeConfig()
	if err != nil {
		var zero SnowflakeConfig
		return zero, err
	}
	if err := e.validateSnowflakeConfig(val); err != nil {
		var zero SnowflakeConfig
		return zero, err
	}
	return val, nil
}

// FromSnowflakeConfig overwrites any union data inside the EnvironmentConfigsGetItem_Config_AnyOf as the provided SnowflakeConfig
func (e *EnvironmentConfigsGetItem_Config_AnyOf) FromSnowflakeConfig(val SnowflakeConfig) error {
	// Validate before storing
	if err := e.validateSnowflakeConfig(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	e.union = bts
	return err
}

// AsRedshiftConfig returns the union data inside the EnvironmentConfigsGetItem_Config_AnyOf as a RedshiftConfig
func (e *EnvironmentConfigsGetItem_Config_AnyOf) AsRedshiftConfig() (RedshiftConfig, error) {
	return runtime.UnmarshalAs[RedshiftConfig](e.union)
}

// AsValidatedRedshiftConfig returns the union data inside the EnvironmentConfigsGetItem_Config_AnyOf as a validated RedshiftConfig
func (e *EnvironmentConfigsGetItem_Config_AnyOf) AsValidatedRedshiftConfig() (RedshiftConfig, error) {
	val, err := e.AsRedshiftConfig()
	if err != nil {
		var zero RedshiftConfig
		return zero, err
	}
	if err := e.validateRedshiftConfig(val); err != nil {
		var zero RedshiftConfig
		return zero, err
	}
	return val, nil
}

// FromRedshiftConfig overwrites any union data inside the EnvironmentConfigsGetItem_Config_AnyOf as the provided RedshiftConfig
func (e *EnvironmentConfigsGetItem_Config_AnyOf) FromRedshiftConfig(val RedshiftConfig) error {
	// Validate before storing
	if err := e.validateRedshiftConfig(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	e.union = bts
	return err
}

// validateAWSS3Config validates a AWSS3Config value
func (e *EnvironmentConfigsGetItem_Config_AnyOf) validateAWSS3Config(val AWSS3Config) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateAWSGlueConfig validates a AWSGlueConfig value
func (e *EnvironmentConfigsGetItem_Config_AnyOf) validateAWSGlueConfig(val AWSGlueConfig) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateDatabricksConfig validates a DatabricksConfig value
func (e *EnvironmentConfigsGetItem_Config_AnyOf) validateDatabricksConfig(val DatabricksConfig) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateSnowflakeConfig validates a SnowflakeConfig value
func (e *EnvironmentConfigsGetItem_Config_AnyOf) validateSnowflakeConfig(val SnowflakeConfig) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateRedshiftConfig validates a RedshiftConfig value
func (e *EnvironmentConfigsGetItem_Config_AnyOf) validateRedshiftConfig(val RedshiftConfig) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

func (e EnvironmentConfigsGetItem_Config_AnyOf) MarshalJSON() ([]byte, error) {
	bts, err := e.union.MarshalJSON()

	return bts, err
}

func (e *EnvironmentConfigsGetItem_Config_AnyOf) UnmarshalJSON(bts []byte) error {
	err := e.union.UnmarshalJSON(bts)

	return err
}

type EnvironmentPlatformConfigGet_Config_AnyOf struct {
	runtime.Either[AWSEnvironmentPlatformConfiguration, DatabricksEnvironmentPlatformConfiguration]
}

func (e *EnvironmentPlatformConfigGet_Config_AnyOf) Validate() error {
	if e.IsA() {
		if v, ok := any(e.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if e.IsB() {
		if v, ok := any(e.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

type GetTechnicalAssetsResponseItem_Configuration_OneOf struct {
	union json.RawMessage
}

func (g *GetTechnicalAssetsResponseItem_Configuration_OneOf) Validate() error {
	// NOTE: Validation is not supported for unions with more than 2 elements.
	// Validating would require unmarshaling against each possible type, which is inefficient.
	// Use AsValidated<Type>() methods to validate after retrieving the specific type.
	return nil
}

// Raw returns the union data inside the GetTechnicalAssetsResponseItem_Configuration_OneOf as bytes
func (g *GetTechnicalAssetsResponseItem_Configuration_OneOf) Raw() json.RawMessage {
	return g.union
}

// AsS3DataOutput returns the union data inside the GetTechnicalAssetsResponseItem_Configuration_OneOf as a S3DataOutput
func (g *GetTechnicalAssetsResponseItem_Configuration_OneOf) AsS3DataOutput() (S3DataOutput, error) {
	return runtime.UnmarshalAs[S3DataOutput](g.union)
}

// AsValidatedS3DataOutput returns the union data inside the GetTechnicalAssetsResponseItem_Configuration_OneOf as a validated S3DataOutput
func (g *GetTechnicalAssetsResponseItem_Configuration_OneOf) AsValidatedS3DataOutput() (S3DataOutput, error) {
	val, err := g.AsS3DataOutput()
	if err != nil {
		var zero S3DataOutput
		return zero, err
	}
	if err := g.validateS3DataOutput(val); err != nil {
		var zero S3DataOutput
		return zero, err
	}
	return val, nil
}

// FromS3DataOutput overwrites any union data inside the GetTechnicalAssetsResponseItem_Configuration_OneOf as the provided S3DataOutput
func (g *GetTechnicalAssetsResponseItem_Configuration_OneOf) FromS3DataOutput(val S3DataOutput) error {
	// Validate before storing
	if err := g.validateS3DataOutput(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	g.union = bts
	return err
}

// AsGlueDataOutput returns the union data inside the GetTechnicalAssetsResponseItem_Configuration_OneOf as a GlueDataOutput
func (g *GetTechnicalAssetsResponseItem_Configuration_OneOf) AsGlueDataOutput() (GlueDataOutput, error) {
	return runtime.UnmarshalAs[GlueDataOutput](g.union)
}

// AsValidatedGlueDataOutput returns the union data inside the GetTechnicalAssetsResponseItem_Configuration_OneOf as a validated GlueDataOutput
func (g *GetTechnicalAssetsResponseItem_Configuration_OneOf) AsValidatedGlueDataOutput() (GlueDataOutput, error) {
	val, err := g.AsGlueDataOutput()
	if err != nil {
		var zero GlueDataOutput
		return zero, err
	}
	if err := g.validateGlueDataOutput(val); err != nil {
		var zero GlueDataOutput
		return zero, err
	}
	return val, nil
}

// FromGlueDataOutput overwrites any union data inside the GetTechnicalAssetsResponseItem_Configuration_OneOf as the provided GlueDataOutput
func (g *GetTechnicalAssetsResponseItem_Configuration_OneOf) FromGlueDataOutput(val GlueDataOutput) error {
	// Validate before storing
	if err := g.validateGlueDataOutput(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	g.union = bts
	return err
}

// AsDatabricksDataOutput returns the union data inside the GetTechnicalAssetsResponseItem_Configuration_OneOf as a DatabricksDataOutput
func (g *GetTechnicalAssetsResponseItem_Configuration_OneOf) AsDatabricksDataOutput() (DatabricksDataOutput, error) {
	return runtime.UnmarshalAs[DatabricksDataOutput](g.union)
}

// AsValidatedDatabricksDataOutput returns the union data inside the GetTechnicalAssetsResponseItem_Configuration_OneOf as a validated DatabricksDataOutput
func (g *GetTechnicalAssetsResponseItem_Configuration_OneOf) AsValidatedDatabricksDataOutput() (DatabricksDataOutput, error) {
	val, err := g.AsDatabricksDataOutput()
	if err != nil {
		var zero DatabricksDataOutput
		return zero, err
	}
	if err := g.validateDatabricksDataOutput(val); err != nil {
		var zero DatabricksDataOutput
		return zero, err
	}
	return val, nil
}

// FromDatabricksDataOutput overwrites any union data inside the GetTechnicalAssetsResponseItem_Configuration_OneOf as the provided DatabricksDataOutput
func (g *GetTechnicalAssetsResponseItem_Configuration_OneOf) FromDatabricksDataOutput(val DatabricksDataOutput) error {
	// Validate before storing
	if err := g.validateDatabricksDataOutput(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	g.union = bts
	return err
}

// AsSnowflakeDataOutput returns the union data inside the GetTechnicalAssetsResponseItem_Configuration_OneOf as a SnowflakeDataOutput
func (g *GetTechnicalAssetsResponseItem_Configuration_OneOf) AsSnowflakeDataOutput() (SnowflakeDataOutput, error) {
	return runtime.UnmarshalAs[SnowflakeDataOutput](g.union)
}

// AsValidatedSnowflakeDataOutput returns the union data inside the GetTechnicalAssetsResponseItem_Configuration_OneOf as a validated SnowflakeDataOutput
func (g *GetTechnicalAssetsResponseItem_Configuration_OneOf) AsValidatedSnowflakeDataOutput() (SnowflakeDataOutput, error) {
	val, err := g.AsSnowflakeDataOutput()
	if err != nil {
		var zero SnowflakeDataOutput
		return zero, err
	}
	if err := g.validateSnowflakeDataOutput(val); err != nil {
		var zero SnowflakeDataOutput
		return zero, err
	}
	return val, nil
}

// FromSnowflakeDataOutput overwrites any union data inside the GetTechnicalAssetsResponseItem_Configuration_OneOf as the provided SnowflakeDataOutput
func (g *GetTechnicalAssetsResponseItem_Configuration_OneOf) FromSnowflakeDataOutput(val SnowflakeDataOutput) error {
	// Validate before storing
	if err := g.validateSnowflakeDataOutput(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	g.union = bts
	return err
}

// AsRedshiftDataOutput returns the union data inside the GetTechnicalAssetsResponseItem_Configuration_OneOf as a RedshiftDataOutput
func (g *GetTechnicalAssetsResponseItem_Configuration_OneOf) AsRedshiftDataOutput() (RedshiftDataOutput, error) {
	return runtime.UnmarshalAs[RedshiftDataOutput](g.union)
}

// AsValidatedRedshiftDataOutput returns the union data inside the GetTechnicalAssetsResponseItem_Configuration_OneOf as a validated RedshiftDataOutput
func (g *GetTechnicalAssetsResponseItem_Configuration_OneOf) AsValidatedRedshiftDataOutput() (RedshiftDataOutput, error) {
	val, err := g.AsRedshiftDataOutput()
	if err != nil {
		var zero RedshiftDataOutput
		return zero, err
	}
	if err := g.validateRedshiftDataOutput(val); err != nil {
		var zero RedshiftDataOutput
		return zero, err
	}
	return val, nil
}

// FromRedshiftDataOutput overwrites any union data inside the GetTechnicalAssetsResponseItem_Configuration_OneOf as the provided RedshiftDataOutput
func (g *GetTechnicalAssetsResponseItem_Configuration_OneOf) FromRedshiftDataOutput(val RedshiftDataOutput) error {
	// Validate before storing
	if err := g.validateRedshiftDataOutput(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	g.union = bts
	return err
}

// validateS3DataOutput validates a S3DataOutput value
func (g *GetTechnicalAssetsResponseItem_Configuration_OneOf) validateS3DataOutput(val S3DataOutput) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateGlueDataOutput validates a GlueDataOutput value
func (g *GetTechnicalAssetsResponseItem_Configuration_OneOf) validateGlueDataOutput(val GlueDataOutput) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateDatabricksDataOutput validates a DatabricksDataOutput value
func (g *GetTechnicalAssetsResponseItem_Configuration_OneOf) validateDatabricksDataOutput(val DatabricksDataOutput) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateSnowflakeDataOutput validates a SnowflakeDataOutput value
func (g *GetTechnicalAssetsResponseItem_Configuration_OneOf) validateSnowflakeDataOutput(val SnowflakeDataOutput) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateRedshiftDataOutput validates a RedshiftDataOutput value
func (g *GetTechnicalAssetsResponseItem_Configuration_OneOf) validateRedshiftDataOutput(val RedshiftDataOutput) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

func (g GetTechnicalAssetsResponseItem_Configuration_OneOf) discriminator(data []byte) (string, error) {
	var discriminator struct {
		Value string `json:"configuration_type"`
	}
	if err := json.Unmarshal(data, &discriminator); err != nil {
		return "", err
	}
	return discriminator.Value, nil
}

func (g GetTechnicalAssetsResponseItem_Configuration_OneOf) ValueByDiscriminator() (any, error) {
	discriminator, err := g.discriminator(g.union)
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "DatabricksDataOutput":
		return g.AsDatabricksDataOutput()
	case "GlueDataOutput":
		return g.AsGlueDataOutput()
	case "RedshiftDataOutput":
		return g.AsRedshiftDataOutput()
	case "S3DataOutput":
		return g.AsS3DataOutput()
	case "SnowflakeDataOutput":
		return g.AsSnowflakeDataOutput()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (g GetTechnicalAssetsResponseItem_Configuration_OneOf) MarshalJSON() ([]byte, error) {
	bts, err := g.union.MarshalJSON()

	return bts, err
}

func (g *GetTechnicalAssetsResponseItem_Configuration_OneOf) UnmarshalJSON(bts []byte) error {
	err := g.union.UnmarshalJSON(bts)

	return err
}

type ModifyGlobalRoleAssignment_RoleID_AnyOf struct {
	runtime.Either[ModifyGlobalRoleAssignment_RoleID_AnyOf_0, string]
}

func (m *ModifyGlobalRoleAssignment_RoleID_AnyOf) Validate() error {
	if m.IsA() {
		if v, ok := any(m.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if m.IsB() {
		if v, ok := any(m.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

type Node_ID_AnyOf struct {
	runtime.Either[string, Node_ID_AnyOf_1]
}

func (n *Node_ID_AnyOf) Validate() error {
	if n.IsA() {
		if v, ok := any(n.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if n.IsB() {
		if v, ok := any(n.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

type NodeData_ID_AnyOf struct {
	runtime.Either[string, NodeData_ID_AnyOf_1]
}

func (n *NodeData_ID_AnyOf) Validate() error {
	if n.IsA() {
		if v, ok := any(n.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if n.IsB() {
		if v, ok := any(n.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

type NodeData_LinkToID_AnyOf struct {
	runtime.Either[string, NodeData_LinkToID_AnyOf_1]
}

func (n *NodeData_LinkToID_AnyOf) Validate() error {
	if n.IsA() {
		if v, ok := any(n.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if n.IsB() {
		if v, ok := any(n.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

type NodeData_DomainID_AnyOf struct {
	runtime.Either[string, NodeData_DomainID_AnyOf_1]
}

func (n *NodeData_DomainID_AnyOf) Validate() error {
	if n.IsA() {
		if v, ok := any(n.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if n.IsB() {
		if v, ok := any(n.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

type NodeData_Assignments_AnyOf_AnyOf struct {
	runtime.Either[AppAuthorizationRoleAssignmentsDataProductSchemaRoleAssignment, AppAuthorizationRoleAssignmentsOutputPortSchemaRoleAssignment]
}

func (n *NodeData_Assignments_AnyOf_AnyOf) Validate() error {
	if n.IsA() {
		if v, ok := any(n.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if n.IsB() {
		if v, ok := any(n.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

type PendingActionResponse_PendingActions_AnyOf struct {
	union json.RawMessage
}

func (p *PendingActionResponse_PendingActions_AnyOf) Validate() error {
	// NOTE: Validation is not supported for unions with more than 2 elements.
	// Validating would require unmarshaling against each possible type, which is inefficient.
	// Use AsValidated<Type>() methods to validate after retrieving the specific type.
	return nil
}

// Raw returns the union data inside the PendingActionResponse_PendingActions_AnyOf as bytes
func (p *PendingActionResponse_PendingActions_AnyOf) Raw() json.RawMessage {
	return p.union
}

// AsDataProductOutputPortPendingAction returns the union data inside the PendingActionResponse_PendingActions_AnyOf as a DataProductOutputPortPendingAction
func (p *PendingActionResponse_PendingActions_AnyOf) AsDataProductOutputPortPendingAction() (DataProductOutputPortPendingAction, error) {
	return runtime.UnmarshalAs[DataProductOutputPortPendingAction](p.union)
}

// AsValidatedDataProductOutputPortPendingAction returns the union data inside the PendingActionResponse_PendingActions_AnyOf as a validated DataProductOutputPortPendingAction
func (p *PendingActionResponse_PendingActions_AnyOf) AsValidatedDataProductOutputPortPendingAction() (DataProductOutputPortPendingAction, error) {
	val, err := p.AsDataProductOutputPortPendingAction()
	if err != nil {
		var zero DataProductOutputPortPendingAction
		return zero, err
	}
	if err := p.validateDataProductOutputPortPendingAction(val); err != nil {
		var zero DataProductOutputPortPendingAction
		return zero, err
	}
	return val, nil
}

// FromDataProductOutputPortPendingAction overwrites any union data inside the PendingActionResponse_PendingActions_AnyOf as the provided DataProductOutputPortPendingAction
func (p *PendingActionResponse_PendingActions_AnyOf) FromDataProductOutputPortPendingAction(val DataProductOutputPortPendingAction) error {
	// Validate before storing
	if err := p.validateDataProductOutputPortPendingAction(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	p.union = bts
	return err
}

// AsTechnicalAssetOutputPortPendingAction returns the union data inside the PendingActionResponse_PendingActions_AnyOf as a TechnicalAssetOutputPortPendingAction
func (p *PendingActionResponse_PendingActions_AnyOf) AsTechnicalAssetOutputPortPendingAction() (TechnicalAssetOutputPortPendingAction, error) {
	return runtime.UnmarshalAs[TechnicalAssetOutputPortPendingAction](p.union)
}

// AsValidatedTechnicalAssetOutputPortPendingAction returns the union data inside the PendingActionResponse_PendingActions_AnyOf as a validated TechnicalAssetOutputPortPendingAction
func (p *PendingActionResponse_PendingActions_AnyOf) AsValidatedTechnicalAssetOutputPortPendingAction() (TechnicalAssetOutputPortPendingAction, error) {
	val, err := p.AsTechnicalAssetOutputPortPendingAction()
	if err != nil {
		var zero TechnicalAssetOutputPortPendingAction
		return zero, err
	}
	if err := p.validateTechnicalAssetOutputPortPendingAction(val); err != nil {
		var zero TechnicalAssetOutputPortPendingAction
		return zero, err
	}
	return val, nil
}

// FromTechnicalAssetOutputPortPendingAction overwrites any union data inside the PendingActionResponse_PendingActions_AnyOf as the provided TechnicalAssetOutputPortPendingAction
func (p *PendingActionResponse_PendingActions_AnyOf) FromTechnicalAssetOutputPortPendingAction(val TechnicalAssetOutputPortPendingAction) error {
	// Validate before storing
	if err := p.validateTechnicalAssetOutputPortPendingAction(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	p.union = bts
	return err
}

// AsDataProductRoleAssignmentPendingAction returns the union data inside the PendingActionResponse_PendingActions_AnyOf as a DataProductRoleAssignmentPendingAction
func (p *PendingActionResponse_PendingActions_AnyOf) AsDataProductRoleAssignmentPendingAction() (DataProductRoleAssignmentPendingAction, error) {
	return runtime.UnmarshalAs[DataProductRoleAssignmentPendingAction](p.union)
}

// AsValidatedDataProductRoleAssignmentPendingAction returns the union data inside the PendingActionResponse_PendingActions_AnyOf as a validated DataProductRoleAssignmentPendingAction
func (p *PendingActionResponse_PendingActions_AnyOf) AsValidatedDataProductRoleAssignmentPendingAction() (DataProductRoleAssignmentPendingAction, error) {
	val, err := p.AsDataProductRoleAssignmentPendingAction()
	if err != nil {
		var zero DataProductRoleAssignmentPendingAction
		return zero, err
	}
	if err := p.validateDataProductRoleAssignmentPendingAction(val); err != nil {
		var zero DataProductRoleAssignmentPendingAction
		return zero, err
	}
	return val, nil
}

// FromDataProductRoleAssignmentPendingAction overwrites any union data inside the PendingActionResponse_PendingActions_AnyOf as the provided DataProductRoleAssignmentPendingAction
func (p *PendingActionResponse_PendingActions_AnyOf) FromDataProductRoleAssignmentPendingAction(val DataProductRoleAssignmentPendingAction) error {
	// Validate before storing
	if err := p.validateDataProductRoleAssignmentPendingAction(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	p.union = bts
	return err
}

// validateDataProductOutputPortPendingAction validates a DataProductOutputPortPendingAction value
func (p *PendingActionResponse_PendingActions_AnyOf) validateDataProductOutputPortPendingAction(val DataProductOutputPortPendingAction) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateTechnicalAssetOutputPortPendingAction validates a TechnicalAssetOutputPortPendingAction value
func (p *PendingActionResponse_PendingActions_AnyOf) validateTechnicalAssetOutputPortPendingAction(val TechnicalAssetOutputPortPendingAction) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateDataProductRoleAssignmentPendingAction validates a DataProductRoleAssignmentPendingAction value
func (p *PendingActionResponse_PendingActions_AnyOf) validateDataProductRoleAssignmentPendingAction(val DataProductRoleAssignmentPendingAction) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

func (p PendingActionResponse_PendingActions_AnyOf) MarshalJSON() ([]byte, error) {
	bts, err := p.union.MarshalJSON()

	return bts, err
}

func (p *PendingActionResponse_PendingActions_AnyOf) UnmarshalJSON(bts []byte) error {
	err := p.union.UnmarshalJSON(bts)

	return err
}

type SelectOption_Value_AnyOf struct {
	runtime.Either[string, bool]
}

func (s *SelectOption_Value_AnyOf) Validate() error {
	if s.IsA() {
		if v, ok := any(s.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if s.IsB() {
		if v, ok := any(s.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}

type TechnicalAsset_Configuration_OneOf struct {
	union json.RawMessage
}

func (t *TechnicalAsset_Configuration_OneOf) Validate() error {
	// NOTE: Validation is not supported for unions with more than 2 elements.
	// Validating would require unmarshaling against each possible type, which is inefficient.
	// Use AsValidated<Type>() methods to validate after retrieving the specific type.
	return nil
}

// Raw returns the union data inside the TechnicalAsset_Configuration_OneOf as bytes
func (t *TechnicalAsset_Configuration_OneOf) Raw() json.RawMessage {
	return t.union
}

// AsS3DataOutput returns the union data inside the TechnicalAsset_Configuration_OneOf as a S3DataOutput
func (t *TechnicalAsset_Configuration_OneOf) AsS3DataOutput() (S3DataOutput, error) {
	return runtime.UnmarshalAs[S3DataOutput](t.union)
}

// AsValidatedS3DataOutput returns the union data inside the TechnicalAsset_Configuration_OneOf as a validated S3DataOutput
func (t *TechnicalAsset_Configuration_OneOf) AsValidatedS3DataOutput() (S3DataOutput, error) {
	val, err := t.AsS3DataOutput()
	if err != nil {
		var zero S3DataOutput
		return zero, err
	}
	if err := t.validateS3DataOutput(val); err != nil {
		var zero S3DataOutput
		return zero, err
	}
	return val, nil
}

// FromS3DataOutput overwrites any union data inside the TechnicalAsset_Configuration_OneOf as the provided S3DataOutput
func (t *TechnicalAsset_Configuration_OneOf) FromS3DataOutput(val S3DataOutput) error {
	// Validate before storing
	if err := t.validateS3DataOutput(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	t.union = bts
	return err
}

// AsGlueDataOutput returns the union data inside the TechnicalAsset_Configuration_OneOf as a GlueDataOutput
func (t *TechnicalAsset_Configuration_OneOf) AsGlueDataOutput() (GlueDataOutput, error) {
	return runtime.UnmarshalAs[GlueDataOutput](t.union)
}

// AsValidatedGlueDataOutput returns the union data inside the TechnicalAsset_Configuration_OneOf as a validated GlueDataOutput
func (t *TechnicalAsset_Configuration_OneOf) AsValidatedGlueDataOutput() (GlueDataOutput, error) {
	val, err := t.AsGlueDataOutput()
	if err != nil {
		var zero GlueDataOutput
		return zero, err
	}
	if err := t.validateGlueDataOutput(val); err != nil {
		var zero GlueDataOutput
		return zero, err
	}
	return val, nil
}

// FromGlueDataOutput overwrites any union data inside the TechnicalAsset_Configuration_OneOf as the provided GlueDataOutput
func (t *TechnicalAsset_Configuration_OneOf) FromGlueDataOutput(val GlueDataOutput) error {
	// Validate before storing
	if err := t.validateGlueDataOutput(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	t.union = bts
	return err
}

// AsDatabricksDataOutput returns the union data inside the TechnicalAsset_Configuration_OneOf as a DatabricksDataOutput
func (t *TechnicalAsset_Configuration_OneOf) AsDatabricksDataOutput() (DatabricksDataOutput, error) {
	return runtime.UnmarshalAs[DatabricksDataOutput](t.union)
}

// AsValidatedDatabricksDataOutput returns the union data inside the TechnicalAsset_Configuration_OneOf as a validated DatabricksDataOutput
func (t *TechnicalAsset_Configuration_OneOf) AsValidatedDatabricksDataOutput() (DatabricksDataOutput, error) {
	val, err := t.AsDatabricksDataOutput()
	if err != nil {
		var zero DatabricksDataOutput
		return zero, err
	}
	if err := t.validateDatabricksDataOutput(val); err != nil {
		var zero DatabricksDataOutput
		return zero, err
	}
	return val, nil
}

// FromDatabricksDataOutput overwrites any union data inside the TechnicalAsset_Configuration_OneOf as the provided DatabricksDataOutput
func (t *TechnicalAsset_Configuration_OneOf) FromDatabricksDataOutput(val DatabricksDataOutput) error {
	// Validate before storing
	if err := t.validateDatabricksDataOutput(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	t.union = bts
	return err
}

// AsSnowflakeDataOutput returns the union data inside the TechnicalAsset_Configuration_OneOf as a SnowflakeDataOutput
func (t *TechnicalAsset_Configuration_OneOf) AsSnowflakeDataOutput() (SnowflakeDataOutput, error) {
	return runtime.UnmarshalAs[SnowflakeDataOutput](t.union)
}

// AsValidatedSnowflakeDataOutput returns the union data inside the TechnicalAsset_Configuration_OneOf as a validated SnowflakeDataOutput
func (t *TechnicalAsset_Configuration_OneOf) AsValidatedSnowflakeDataOutput() (SnowflakeDataOutput, error) {
	val, err := t.AsSnowflakeDataOutput()
	if err != nil {
		var zero SnowflakeDataOutput
		return zero, err
	}
	if err := t.validateSnowflakeDataOutput(val); err != nil {
		var zero SnowflakeDataOutput
		return zero, err
	}
	return val, nil
}

// FromSnowflakeDataOutput overwrites any union data inside the TechnicalAsset_Configuration_OneOf as the provided SnowflakeDataOutput
func (t *TechnicalAsset_Configuration_OneOf) FromSnowflakeDataOutput(val SnowflakeDataOutput) error {
	// Validate before storing
	if err := t.validateSnowflakeDataOutput(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	t.union = bts
	return err
}

// AsRedshiftDataOutput returns the union data inside the TechnicalAsset_Configuration_OneOf as a RedshiftDataOutput
func (t *TechnicalAsset_Configuration_OneOf) AsRedshiftDataOutput() (RedshiftDataOutput, error) {
	return runtime.UnmarshalAs[RedshiftDataOutput](t.union)
}

// AsValidatedRedshiftDataOutput returns the union data inside the TechnicalAsset_Configuration_OneOf as a validated RedshiftDataOutput
func (t *TechnicalAsset_Configuration_OneOf) AsValidatedRedshiftDataOutput() (RedshiftDataOutput, error) {
	val, err := t.AsRedshiftDataOutput()
	if err != nil {
		var zero RedshiftDataOutput
		return zero, err
	}
	if err := t.validateRedshiftDataOutput(val); err != nil {
		var zero RedshiftDataOutput
		return zero, err
	}
	return val, nil
}

// FromRedshiftDataOutput overwrites any union data inside the TechnicalAsset_Configuration_OneOf as the provided RedshiftDataOutput
func (t *TechnicalAsset_Configuration_OneOf) FromRedshiftDataOutput(val RedshiftDataOutput) error {
	// Validate before storing
	if err := t.validateRedshiftDataOutput(val); err != nil {
		return err
	}
	bts, err := json.Marshal(val)
	t.union = bts
	return err
}

// validateS3DataOutput validates a S3DataOutput value
func (t *TechnicalAsset_Configuration_OneOf) validateS3DataOutput(val S3DataOutput) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateGlueDataOutput validates a GlueDataOutput value
func (t *TechnicalAsset_Configuration_OneOf) validateGlueDataOutput(val GlueDataOutput) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateDatabricksDataOutput validates a DatabricksDataOutput value
func (t *TechnicalAsset_Configuration_OneOf) validateDatabricksDataOutput(val DatabricksDataOutput) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateSnowflakeDataOutput validates a SnowflakeDataOutput value
func (t *TechnicalAsset_Configuration_OneOf) validateSnowflakeDataOutput(val SnowflakeDataOutput) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

// validateRedshiftDataOutput validates a RedshiftDataOutput value
func (t *TechnicalAsset_Configuration_OneOf) validateRedshiftDataOutput(val RedshiftDataOutput) error {
	if v, ok := any(val).(runtime.Validator); ok {
		return v.Validate()
	}
	return nil
}

func (t TechnicalAsset_Configuration_OneOf) discriminator(data []byte) (string, error) {
	var discriminator struct {
		Value string `json:"configuration_type"`
	}
	if err := json.Unmarshal(data, &discriminator); err != nil {
		return "", err
	}
	return discriminator.Value, nil
}

func (t TechnicalAsset_Configuration_OneOf) ValueByDiscriminator() (any, error) {
	discriminator, err := t.discriminator(t.union)
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "DatabricksDataOutput":
		return t.AsDatabricksDataOutput()
	case "GlueDataOutput":
		return t.AsGlueDataOutput()
	case "RedshiftDataOutput":
		return t.AsRedshiftDataOutput()
	case "S3DataOutput":
		return t.AsS3DataOutput()
	case "SnowflakeDataOutput":
		return t.AsSnowflakeDataOutput()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t TechnicalAsset_Configuration_OneOf) MarshalJSON() ([]byte, error) {
	bts, err := t.union.MarshalJSON()

	return bts, err
}

func (t *TechnicalAsset_Configuration_OneOf) UnmarshalJSON(bts []byte) error {
	err := t.union.UnmarshalJSON(bts)

	return err
}

type ValidationError_Loc_AnyOf struct {
	runtime.Either[string, int]
}

func (v *ValidationError_Loc_AnyOf) Validate() error {
	if v.IsA() {
		if v, ok := any(v.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if v.IsB() {
		if v, ok := any(v.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}
