name: Nightly Docker Compose Test
on:
  pull_request:
    branches: '*'
permissions:
  contents: read

jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Test Docker Compose
        run: docker compose up -d
