name: Nightly Docker Compose Test
on:
  pull_request:
    branches: '*'
permissions:
  contents: read

jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Test Docker Compose
        id: run_command
        run: |
            STATUS_CODE=$(docker compose up -d && curl -s -o /dev/null -w "%{http_code}" localhost:8080)
            echo "Status code: $STATUS_CODE"
            # Set the output for GitHub Actions
            echo "::set-output name=status_code::$STATUS_CODE"
      - name: Check command success
        if: ${{ steps.run_command.outputs.status_code == '200' }}
        run: echo "Command was successful (200)"

      - name: Check command failure
        if: ${{ steps.run_command.outputs.status_code != '200' }}
        run: |
          echo "Command failed with status code ${{ steps.run_command.outputs.status_code }}"
          exit 1
