name: Release workflow

on:
  push:
    tags:
      - '*'

permissions:
  id-token: write
  contents: write

jobs:
  create-gh-release-notes:
    name: Create GitHub release notes and release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
      - name: Create release notes in github
        env:
          tag: ${{ github.ref_name }}
        id: create_release_notes
        run: |
          VERSION="${tag#v}"
          echo "Release notes for version $VERSION"
          RELEASEVERSION="[$VERSION]"
          echo "Version: $RELEASEVERSION"
          RELEASENOTES=$(awk -v ver="$RELEASEVERSION" '/^## / { if (p) { exit }; if ($2 == ver) { p=1; next } } p && NF' docs/docs/release-notes.md)
          {
          echo 'RELEASENOTES<<EOF'
          echo "${RELEASENOTES}"
          echo EOF
          } >> $GITHUB_OUTPUT

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          echo "Creating release for version $tag"
          echo "${{ steps.create_release_notes.outputs.RELEASENOTES }}"
          gh release create "$tag" --title "$tag" --notes "${{ steps.create_release_notes.outputs.RELEASENOTES }}"
          echo "Release created successfully"
