# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release

on:
  push:
    #tags:
    #  - '*'
    branches:
      - rework-docs-naming

permissions:
  id-token: write
  contents: read

jobs:
  release-docs:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::553817834567:role/github-actions-docs
          role-session-name: GithubActions
          aws-region: eu-west-1
      - name: Install AWS CLI v2
        uses: unfor19/install-aws-cli-action@v1
        with:
          arch: amd64
      - name: Release portal docs
        working-directory: docs
        run: |
          npm run build
          echo aws s3 cp build/ s3://data-product-portal-user-docs-tfhgye/ --recursive
